import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import DateTile from '../../components/dashboard/DateTile.jsx';
import RecordSection from '../../components/records/RecordSection.jsx';
import { formatEncounter } from '../../services/dateTimeService.js';
import { patientApiErrorMessage, patientApiService } from '../../services/patientApiService.js';
import '../../styles/patient-records.css';

export default function PatientRecordDetail() {
  const { id } = useParams(); const [record, setRecord] = useState(null); const [status, setStatus] = useState('loading'); const [message, setMessage] = useState('');
  useEffect(() => { patientApiService.getRecord(id).then(value => { setRecord(value); setStatus('ready'); }).catch(reason => { setMessage(patientApiErrorMessage(reason, 'This medical record was not found.')); setStatus(reason?.status === 404 ? 'not-found' : 'error'); }); }, [id]);
  return <div className="patient-records"><Link className="record-back" to="/patient/records">← Back to My Records</Link><header className="records-heading"><h1>Medical Record Details</h1><p>View your consultation, diagnosis, prescriptions, and doctor’s notes.</p></header>{status === 'loading' && <RecordSection title="Loading medical record"><p aria-live="polite">Please wait…</p></RecordSection>}{status !== 'loading' && status !== 'ready' && <RecordSection title={status === 'not-found' ? 'Medical record not found' : 'Unable to load medical record'}><p role="alert">{message}</p></RecordSection>}{record && <div className="records-layout"><div className="record-detail-sections"><section className="record-card record-summary"><DateTile value={record.encounter_at} /><div><h2>{record.visitType}</h2><p><strong>{record.doctor}</strong><br />{record.specialty}</p><p><time>{formatEncounter(record.encounter_at)}</time><br />Philippine time</p></div></section><RecordSection title="Diagnosis"><p className="record-callout">{record.diagnosis}</p></RecordSection><RecordSection title="Prescriptions">{record.prescriptions.length ? <ul className="record-prescriptions">{record.prescriptions.map(item => <li key={item.id}><h3>{item.medicine}</h3><dl><div><dt>Dosage</dt><dd>{item.dosage}</dd></div><div><dt>Instructions</dt><dd>{item.instructions || 'No additional instructions recorded.'}</dd></div></dl></li>)}</ul> : <p>No prescriptions recorded for this visit.</p>}</RecordSection><RecordSection title="Doctor’s Notes"><p className="record-callout">{record.notes || 'No doctor’s notes recorded.'}</p></RecordSection><RecordSection title="Follow-up Instructions"><p>{record.follow_up || 'No follow-up instructions recorded.'}</p></RecordSection></div><aside className="record-detail-sections">{record.certificates.length > 0 && <RecordSection title="Related Documents">{record.certificates.map(certificate => <Link className="record-certificate" key={certificate.id} to={'/patient/certificates/' + certificate.id}><strong>{certificate.purpose}</strong><span>View Certificate →</span></Link>)}</RecordSection>}<RecordSection title="About This Record"><p>This is a read-only medical record created at Arion Health Clinic.</p></RecordSection></aside></div>}</div>;
}
