import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import StatusBadge from '../../components/dashboard/StatusBadge.jsx';
import CertificateFacts from '../../components/certificates/CertificateFacts.jsx';
import CertificatePreview from '../../components/certificates/CertificatePreview.jsx';
import { formatEncounter } from '../../services/dateTimeService.js';
import { patientApiErrorMessage, patientApiService } from '../../services/patientApiService.js';
import '../../styles/patient-certificates.css';

export default function PatientCertificateDetail() {
  const { id } = useParams(); const [certificate, setCertificate] = useState(null); const [status, setStatus] = useState('loading'); const [message, setMessage] = useState('');
  useEffect(() => { patientApiService.getCertificate(id).then(value => { setCertificate(value); setStatus('ready'); }).catch(reason => { setMessage(patientApiErrorMessage(reason, 'This certificate was not found.')); setStatus(reason?.status === 404 ? 'not-found' : 'error'); }); }, [id]);
  return <div className="patient-certificates"><Link className="certificate-back" to="/patient/certificates">← Back to My Certificates</Link><header className="certificates-heading"><h1>Certificate Details</h1><p>View the details of your issued medical certificate.</p></header>{status === 'loading' && <section className="certificate-card" aria-live="polite">Loading certificate…</section>}{status !== 'loading' && status !== 'ready' && <section className="certificate-card" role="alert"><h2>{status === 'not-found' ? 'Certificate not found' : 'Unable to load certificate'}</h2><p>{message}</p></section>}{certificate && <div className="certificates-layout"><div className="certificate-sections"><section className="certificate-card"><div className="certificate-title"><h2>{certificate.purpose}</h2><StatusBadge status={certificate.status} /></div><CertificateFacts certificate={certificate} /></section><section className="certificate-card"><h2>Certificate Preview</h2><CertificatePreview certificate={certificate} /><div className="certificate-download"><button type="button" className="action-link" disabled>Download PDF</button><p>PDF generation will be added later.</p></div></section></div><aside className="certificate-sections"><section className="certificate-card"><h2>Related Medical Record</h2>{certificate.relatedRecord ? <Link className="certificate-related" to={'/patient/records/' + certificate.relatedRecord.id}><strong>{certificate.relatedRecord.visitType}</strong><span>{formatEncounter(certificate.relatedRecord.encounter_at)} · Philippine time</span><span>View Record →</span></Link> : <p>No medical record is linked to this certificate.</p>}</section><section className="certificate-card"><h2>About This Certificate</h2><p>This is a read-only certificate issued by your doctor.</p></section></aside></div>}</div>;
}
