import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import FormField from '../../components/public/FormField.jsx';
import DashboardIcon from '../../components/dashboard/DashboardIcon.jsx';
import StatusBadge from '../../components/dashboard/StatusBadge.jsx';
import BookingStep from '../../components/booking/BookingStep.jsx';
import BookingCalendar from '../../components/booking/BookingCalendar.jsx';
import { formatBookingDate, formatSlot, slotRange } from '../../services/dateTimeService.js';
import { patientApiErrorMessage, patientApiService, patientBookingDates, patientVisitTypes } from '../../services/patientApiService.js';
import '../../styles/patient-booking.css';

const initial = { service: '', doctor: '', date: '', time: '', reason: '' };
export default function PatientBooking() {
  const [values, setValues] = useState(initial); const [doctors, setDoctors] = useState([]); const [slotsByDate, setSlotsByDate] = useState({}); const [errors, setErrors] = useState({}); const [message, setMessage] = useState(''); const [confirmation, setConfirmation] = useState(null); const [loading, setLoading] = useState(true); const [loadingSlots, setLoadingSlots] = useState(false); const [busy, setBusy] = useState(false); const errorRef = useRef(null); const dates = patientBookingDates();
  useEffect(() => { patientApiService.getDoctors().then(setDoctors).catch(reason => setMessage(patientApiErrorMessage(reason, 'No doctors are currently available.'))).finally(() => setLoading(false)); }, []);
  useEffect(() => { let active = true; if (!values.doctor) { setSlotsByDate({}); return; } setLoadingSlots(true); patientApiService.getBookableDates(values.doctor, dates).then(result => active && setSlotsByDate(result)).catch(reason => active && setMessage(patientApiErrorMessage(reason, 'Unable to load appointment availability.'))).finally(() => active && setLoadingSlots(false)); return () => { active = false; }; }, [values.doctor]);
  const doctor = doctors.find(item => item.id === values.doctor); const service = patientVisitTypes.find(item => item.id === values.service); const slots = slotsByDate[values.date] ?? []; const availableDates = new Set(Object.entries(slotsByDate).filter(([, value]) => value.length).map(([date]) => date));
  function update(field, value) { setValues(current => ({ ...current, [field]: value, ...(['doctor', 'date'].includes(field) ? { time: '' } : {}), ...(field === 'doctor' ? { date: '' } : {}) })); setErrors({}); setMessage(''); }
  async function refreshDate() { if (!values.doctor || !values.date) return; const next = await patientApiService.getAvailableSlots(values.doctor, values.date); setSlotsByDate(current => ({ ...current, [values.date]: next })); }
  async function submit(event) { event.preventDefault(); const nextErrors = {}; if (!service) nextErrors.service = 'Select a visit type.'; if (!doctor) nextErrors.doctor = 'Select a doctor.'; if (!availableDates.has(values.date)) nextErrors.date = 'Select an available date within the next 14 days.'; if (!slots.some(slot => slot.time === values.time)) nextErrors.time = 'Select an available time slot.'; if (!values.reason.trim()) nextErrors.reason = 'Enter a reason for your visit.'; if (Object.keys(nextErrors).length) { setErrors(nextErrors); requestAnimationFrame(() => errorRef.current?.focus()); return; } setBusy(true); try { setConfirmation(await patientApiService.createAppointment(values)); } catch (reason) { const text = patientApiErrorMessage(reason, 'Unable to create the appointment.'); setMessage(text); if (reason?.status === 409) { setValues(current => ({ ...current, time: '' })); await refreshDate().catch(() => {}); } } finally { setBusy(false); } }
  const fieldError = name => errors[name] && <p className="booking-error">{errors[name]}</p>;
  if (confirmation) return <div className="patient-booking"><section className="booking-card booking-success"><span className="success-check">✓</span><h1>Appointment request created</h1><p>Your appointment was saved and is awaiting clinic confirmation.</p><StatusBadge status={confirmation.status} /><dl><div><dt>Service</dt><dd>{confirmation.service}</dd></div><div><dt>Doctor</dt><dd>{confirmation.doctor}</dd></div><div><dt>Date</dt><dd>{formatBookingDate(confirmation.date)}</dd></div><div><dt>Time</dt><dd>{confirmation.timeLabel} · Philippine time</dd></div><div><dt>Reason</dt><dd>{confirmation.reason}</dd></div></dl><div className="booking-success-actions"><Link className="action-link booking-primary" to="/patient/appointments">View My Appointments</Link><Link className="action-link" to="/patient/dashboard">Back to Dashboard</Link></div></section></div>;
  return <div className="patient-booking"><Link className="booking-back" to="/patient/dashboard">← Back to Dashboard</Link><form className="booking-layout" onSubmit={submit} noValidate><div className="booking-main"><header className="booking-intro"><div><h1>Book Appointment</h1><p>Schedule a consultation with your healthcare provider.</p></div><DashboardIcon name="calendar" /></header><p className="booking-notice">Routine consultations only. Emergency visits cannot be booked here.</p>{message && <p className="booking-errors" role="alert">{message}</p>}{Object.keys(errors).length > 0 && <div className="booking-errors" role="alert" tabIndex="-1" ref={errorRef}><strong>Please complete your appointment details.</strong></div>}<div className="booking-steps">
    <BookingStep number="1" title="Select Visit Type or Service"><FormField label="Visit type / service" name="booking-service" value={values.service} onChange={event => update('service', event.target.value)}><option value="">Select a service</option>{patientVisitTypes.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</FormField>{fieldError('service')}</BookingStep>
    <BookingStep number="2" title="Select Doctor"><FormField label="Doctor" name="booking-doctor" value={values.doctor} onChange={event => update('doctor', event.target.value)} disabled={loading}><option value="">{loading ? 'Loading doctors…' : 'Select a doctor'}</option>{doctors.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</FormField>{doctor && <p className="booking-hint">{doctor.specialty}</p>}{fieldError('doctor')}</BookingStep>
    <BookingStep number="3" title="Select Date" description="Choose an available date from today through the next 14 days."><BookingCalendar value={values.date} doctorId={values.doctor} availableDates={availableDates} loading={loadingSlots} onChange={date => update('date', date)} invalid={!!errors.date} />{fieldError('date')}</BookingStep>
    <BookingStep number="4" title="Select Time Slot" description="Available 30-minute slots · Philippine time."><fieldset className="booking-slots"><legend className="booking-sr-only">Available appointment time</legend>{slots.map(slot => <label key={slot.time} className="booking-slot"><input type="radio" name="booking-time" value={slot.time} checked={values.time === slot.time} onChange={() => update('time', slot.time)} /><span>{formatSlot(slot.time)}</span></label>)}</fieldset><p className="booking-hint">{!values.doctor || !values.date ? 'Select a doctor and date to see available times.' : loadingSlots ? 'Loading available times…' : !slots.length ? 'No available slots on this date.' : 'Only currently available slots are shown.'}</p>{fieldError('time')}</BookingStep>
    <BookingStep number="5" title="Reason for Visit"><textarea rows="3" value={values.reason} onChange={event => update('reason', event.target.value)} placeholder="Briefly describe your concern" />{fieldError('reason')}</BookingStep>
  </div></div><aside className="booking-summary booking-card"><h2>Booking Summary</h2><dl><div><dt>Service</dt><dd>{service?.name ?? 'Not selected'}</dd></div><div><dt>Doctor</dt><dd>{doctor?.name ?? 'Not selected'}</dd></div><div><dt>Date</dt><dd>{formatBookingDate(values.date)}</dd></div><div><dt>Time</dt><dd>{values.time ? slotRange(values.time) : 'Not selected'}</dd></div><div><dt>Reason</dt><dd>{values.reason.trim() || 'Not provided'}</dd></div></dl><button className="action-link booking-primary" type="submit" disabled={busy || loadingSlots}>{busy ? 'Confirming…' : 'Confirm Appointment'}</button><Link className="action-link booking-cancel" to="/patient/dashboard">Cancel</Link></aside></form></div>;
}
