import { useEffect, useRef, useState } from 'react';
import FormField from '../../components/public/FormField.jsx';
import { useAuth } from '../../auth/AuthContext.jsx';
import { clinicToday } from '../../services/dateTimeService.js';
import { patientApiErrorMessage, patientApiService, patientIsSenior, patientProfileSexOptions, validatePatientProfile } from '../../services/patientApiService.js';
import '../../styles/patient-profile.css';

const toForm = profile => ({ ...profile, allergies: (profile.allergies ?? []).join(', ') });
export default function PatientProfile() {
  const { refreshCurrentUser } = useAuth();
  const [values, setValues] = useState(null); const [saved, setSaved] = useState(null); const [errors, setErrors] = useState({}); const [message, setMessage] = useState(''); const [loadError, setLoadError] = useState(''); const [busy, setBusy] = useState(false); const errorRef = useRef(null);
  useEffect(() => { let active = true; patientApiService.getProfile().then(profile => { if (active) { const form = toForm(profile); setValues(form); setSaved(form); } }).catch(reason => active && setLoadError(patientApiErrorMessage(reason, 'Patient profile was not found.'))); return () => { active = false; }; }, []);
  if (loadError) return <section className="profile-card" role="alert"><h1>Unable to load your profile</h1><p>{loadError}</p></section>;
  if (!values) return <section className="profile-card" aria-live="polite"><h1>Loading your profile…</h1></section>;
  const change = (key, value) => { setValues(current => ({ ...current, [key]: value })); setErrors(current => ({ ...current, [key]: undefined })); setMessage(''); };
  const field = (key, label, props = {}) => <div><FormField name={'profile-' + key} label={label} value={values[key]} onChange={event => change(key, event.target.value)} aria-invalid={!!errors[key]} {...props} />{errors[key] && <p className="profile-error">{errors[key]}</p>}</div>;
  async function save(event) { event.preventDefault(); const nextErrors = validatePatientProfile(values); if (Object.keys(nextErrors).length) { setErrors(nextErrors); requestAnimationFrame(() => errorRef.current?.focus()); return; } setBusy(true); try { const updated = toForm(await patientApiService.updateProfile(values)); setValues(updated); setSaved(updated); setMessage('Your profile was saved.'); await refreshCurrentUser(); } catch (reason) { setMessage(patientApiErrorMessage(reason, 'Unable to save your profile.')); } finally { setBusy(false); } }
  return <div className="patient-profile"><header className="profile-heading"><h1>My Profile</h1><p>Update your personal information, emergency contact, and health details.</p><p className="profile-note">Fields marked * are required.</p></header><p role="status" className="profile-message">{message}</p><div className="profile-layout"><form onSubmit={save} noValidate>
    {Object.values(errors).some(Boolean) && <div ref={errorRef} tabIndex={-1} role="alert" className="profile-errors"><strong>Please check the highlighted fields.</strong></div>}
    <section className="profile-card"><h2>Personal Information</h2><div className="profile-fields">{field('fullName', 'Full name *', { required: true })}{field('dob', 'Date of birth *', { required: true, type: 'date', max: clinicToday() })}<div><label htmlFor="profile-sex">Sex *</label><select id="profile-sex" value={values.sex} onChange={event => change('sex', event.target.value)}><option value="">Select an option</option>{patientProfileSexOptions.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select>{errors.sex && <p className="profile-error">{errors.sex}</p>}</div>{field('contactNumber', 'Contact number *', { required: true, type: 'tel' })}{field('address', 'Address (optional)')}</div></section>
    <section className="profile-card"><h2>Emergency Contact <small>(optional)</small></h2><div className="profile-fields profile-emergency">{field('emergencyName', 'Emergency contact name')}{field('emergencyNumber', 'Emergency contact number', { type: 'tel' })}{field('relationship', 'Relationship')}</div></section>
    <section className="profile-card"><h2>Health Information</h2><div className="profile-fields"><div><label htmlFor="profile-allergies">Allergies</label><textarea id="profile-allergies" value={values.allergies} readOnly /><p className="profile-note">Allergies are read-only clinic information.</p></div><div><fieldset><legend>Person with Disability (PWD) status</legend><div className="profile-radios">{[[false, 'No'], [true, 'Yes']].map(([value, label]) => <label key={label}><input type="radio" name="profile-pwd" checked={values.isPwd === value} onChange={() => change('isPwd', value)} />{label}</label>)}</div></fieldset><p className="profile-senior">Senior citizen: <strong>{patientIsSenior(values.dob) ? 'Yes' : 'No'}</strong></p><p className="profile-note">Calculated from date of birth.</p></div></div><div className="profile-actions"><button type="button" className="action-link" disabled={busy} onClick={() => { setValues({ ...saved }); setErrors({}); setMessage('Unsaved changes were discarded.'); }}>Cancel</button><button type="submit" className="action-link profile-save" disabled={busy}>{busy ? 'Saving…' : 'Save Changes'}</button></div></section>
  </form><aside><section className="profile-card"><h2>Account</h2><p>Password changes are handled through account recovery.</p><button type="button" className="action-link" disabled>Change Password</button></section></aside></div></div>;
}
