import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import StatusBadge from '../../components/dashboard/StatusBadge.jsx';
import { clinicToday, formatBookingDate } from '../../services/dateTimeService.js';
import { staffApiErrorMessage, staffApiService, staffQueueActions } from '../../services/staffApiService.js';
import '../../styles/staff-queue.css';

const time=value=>value?new Date(value).toLocaleTimeString('en-US',{timeZone:'Asia/Manila',hour:'numeric',minute:'2-digit'}):'Not checked in';
export default function StaffQueue(){
  const [state,setState]=useState({loading:true,appointments:[],waiting:[],error:''}); const [selectedId,setSelectedId]=useState(null); const [confirmation,setConfirmation]=useState(null); const [message,setMessage]=useState(''); const [submitting,setSubmitting]=useState(false);
  const load=useCallback(async()=>{setState(old=>({...old,loading:true,error:''}));try{const [appointments,waiting]=await Promise.all([staffApiService.getAppointments(clinicToday()),staffApiService.getQueue()]);setState({loading:false,appointments,waiting,error:''});}catch(error){setState({loading:false,appointments:[],waiting:[],error:staffApiErrorMessage(error,'Unable to load the queue.')});}},[]); useEffect(()=>{load();},[load]);
  const selected=[...state.waiting,...state.appointments].find(item=>item.id===selectedId); const actions=staffQueueActions(selected); const waitingIds=new Set(state.waiting.map(item=>item.id)); const notCheckedIn=state.appointments.filter(item=>!item.check_in_at&&['pending','confirmed'].includes(item.status)); const finished=state.appointments.filter(item=>['completed','cancelled','no_show'].includes(item.status));
  async function act(action,value){setSubmitting(true);setConfirmation(null);try{if(action==='checkIn')await staffApiService.checkIn(selected.id);if(action==='noShow')await staffApiService.noShow(selected.id);if(action==='priority')await staffApiService.updatePriority(selected.id,value);setMessage(action==='checkIn'?`${selected.patientName} checked in.`:action==='noShow'?`${selected.patientName} marked no-show.`:'Queue priority updated.');await load();}catch(error){setState(old=>({...old,error:staffApiErrorMessage(error,'Unable to update this appointment.')}));}finally{setSubmitting(false);}}
  function section(title,items,empty,waiting=false){return <section className="queue-panel"><h2>{title} <span>({items.length})</span></h2>{items.length?<ol className="queue-list">{items.map((item,index)=><li key={item.id}><button className="queue-patient" aria-pressed={selectedId===item.id} onClick={()=>{setSelectedId(item.id);setConfirmation(null);}}><span className="queue-person">{waiting&&<span className="queue-position">{index+1}</span>}<strong>{item.patientName}</strong><span>{item.timeLabel} · {item.doctorName}</span></span><span className="queue-labels">{waiting&&<span className={'badge priority-'+item.tier}>{item.priorityLabel}</span>}<StatusBadge status={item.status}/><span>{waiting?'Waiting · ':''}{time(item.check_in_at)}</span><span className="queue-view">View details →</span></span></button></li>)}</ol>:<p className="queue-empty">{empty}</p>}</section>}
  return <div className="staff-queue"><header className="queue-heading"><div><h1>Queue / Check-in</h1><p>Manage today’s waiting patients and check-in flow.</p></div><p>{formatBookingDate(clinicToday())}<br/>Arion Health Clinic</p></header><nav className="queue-links"><Link className="action-link" to="/staff/calendar">Full Calendar</Link><Link className="action-link" to="/staff/patients/new">Register Walk-in</Link></nav>
    {state.loading?<p role="status">Loading queue…</p>:<><div className="queue-counts">{[['Waiting patients',state.waiting.length],['Checked in',state.appointments.filter(item=>item.check_in_at).length],['Urgent / Senior / PWD waiting',state.waiting.filter(item=>item.tier<2).length]].map(([label,count])=><div className="queue-panel" key={label}><span>{label}</span><strong>{count}</strong></div>)}</div><p className="queue-note">Philippine time · Live queue order comes from the clinic API.</p><p role="status">{message}</p>{state.error&&<p role="alert">{state.error}</p>}<div className="queue-layout"><div className="queue-sections">{section('Waiting queue',state.waiting,'No patients currently waiting.',true)}{section('Not checked in',notCheckedIn,'No eligible check-ins remaining today.')}{section('Completed / Cancelled / No-show',finished,'No completed, cancelled, or no-show appointments today.')}</div><aside className="queue-panel queue-details"><h2>Selected appointment</h2>{selected?<><h3>{selected.patientName}</h3><StatusBadge status={selected.status}/><dl><dt>Appointment time</dt><dd>{selected.timeLabel}</dd><dt>Doctor</dt><dd>{selected.doctorName}</dd><dt>Check-in time</dt><dd>{time(selected.check_in_at)}</dd><dt>Queue priority</dt><dd>{waitingIds.has(selected.id)?selected.priorityLabel:selected.priority==='urgent'?'Urgent':'Normal'}</dd></dl><div className="queue-actions">{actions.checkIn&&<button disabled={submitting} onClick={()=>act('checkIn')}>Check In</button>}{actions.noShow&&<button disabled={submitting} onClick={()=>setConfirmation('noShow')}>Mark No-show</button>}{actions.priority&&<button disabled={submitting||selected.priority==='urgent'} onClick={()=>act('priority','urgent')}>Set Urgent</button>}{actions.priority&&selected.priority==='urgent'&&<button disabled={submitting} onClick={()=>act('priority','normal')}>Set Normal</button>}</div>{confirmation&&<div className="queue-confirm"><p>Confirm this patient did not attend the scheduled appointment.</p><button disabled={submitting} onClick={()=>act('noShow')}>Confirm no-show</button><button onClick={()=>setConfirmation(null)}>Keep current status</button></div>}{!actions.checkIn&&!actions.noShow&&!actions.priority&&<p>This appointment is view-only. The assigned doctor completes the consultation after saving its medical record.</p>}</>:<p>Select a patient to view operational details and available actions.</p>}<div className="queue-reminder"><h3>Queue priority</h3><p>Urgent → Senior / PWD → Normal.</p><p>The backend derives Senior/PWD and orders each tier by check-in time.</p></div></aside></div></>}
  </div>;
}
