import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import StatusBadge from '../../components/dashboard/StatusBadge.jsx';
import { clinicToday, formatBookingDate, shiftCalendarDate } from '../../services/dateTimeService.js';
import { staffApiErrorMessage, staffApiService, staffCalendarActions } from '../../services/staffApiService.js';
import '../../styles/staff-calendar.css';

const statuses = ['pending','confirmed','completed','cancelled','no_show'];
const clinicTime=value=>new Date(value).toLocaleTimeString('en-US',{timeZone:'Asia/Manila',hour:'numeric',minute:'2-digit'});
function arrivalLabel(item){
  if(item.check_in_at)return 'Arrived / Confirmed';
  if(item.status==='pending')return 'Scheduled / Pending';
  if(item.status==='confirmed')return 'Scheduled / Confirmed';
  if(item.status==='completed')return 'Completed';
  if(item.status==='cancelled')return 'Cancelled';
  if(item.status==='no_show')return 'No-show';
  return 'Scheduled';
}
export default function StaffCalendar() {
  const today=clinicToday(); const [date,setDate]=useState(today); const [doctor,setDoctor]=useState(''); const [mobileDoctor,setMobileDoctor]=useState(null); const [status,setStatus]=useState(''); const [selectedId,setSelectedId]=useState(null); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [cancelling,setCancelling]=useState(false); const [confirmingNoShow,setConfirmingNoShow]=useState(false); const [loading,setLoading]=useState(true); const [submitting,setSubmitting]=useState(false); const [appointments,setAppointments]=useState([]); const [currentTime,setCurrentTime]=useState(()=>new Date());
  const load=useCallback(async()=>{setLoading(true);setError('');try{setAppointments(await staffApiService.getAppointments(date));}catch(reason){setAppointments([]);setError(staffApiErrorMessage(reason,'Unable to load appointments for this date.'));}finally{setLoading(false);}},[date]);
  useEffect(()=>{load();},[load]);
  useEffect(()=>{const timer=setInterval(()=>setCurrentTime(new Date()),1000);return()=>clearInterval(timer);},[]);
  const doctors=[...new Map(appointments.map(item=>[item.doctor_id,item.doctorName])).entries()]; const shown=appointments.filter(item=>(!doctor||item.doctor_id===doctor)&&(!status||item.status===status)); const visibleDoctors=doctors.filter(([id])=>shown.some(item=>item.doctor_id===id)); const mobileIndex=Math.max(0,visibleDoctors.findIndex(([id])=>id===mobileDoctor)); const selected=appointments.find(item=>item.id===selectedId); const actions=staffCalendarActions(selected,today,currentTime);
  function resetSelectionState(){setCancelling(false);setConfirmingNoShow(false);}
  function changeDate(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return;setDate(value);setDoctor('');setMobileDoctor(null);setSelectedId(null);setMessage('');setError('');resetSelectionState();}
  async function update(action){setSubmitting(true);setError('');try{if(action==='arrival')await staffApiService.checkIn(selected.id);else if(action==='noShow')await staffApiService.noShow(selected.id);else await staffApiService.cancel(selected.id);setMessage(action==='arrival'?'Arrival confirmed. Patient added to the active queue.':action==='noShow'?'Appointment marked No-show.':'Appointment cancelled.');setSelectedId(null);resetSelectionState();await load();}catch(reason){setError(staffApiErrorMessage(reason,action==='arrival'?'Unable to confirm arrival. Refresh and try again.':action==='noShow'?'Unable to mark this appointment No-show. Refresh and try again.':'Unable to update this appointment.'));}finally{setSubmitting(false);}}
  return <div className="staff-calendar"><header className="calendar-title"><div><h1>Full Calendar</h1><p>View scheduled appointments and their current state.</p></div><Link className="action-link" to="/staff/patients/new">Register Walk-in</Link></header>
    <div className="calendar-controls"><div className="calendar-date"><button aria-label="Previous day" onClick={()=>changeDate(shiftCalendarDate(date,-1))}>‹</button><label>Selected date<input type="date" value={date} onChange={event=>changeDate(event.target.value)}/></label><button aria-label="Next day" onClick={()=>changeDate(shiftCalendarDate(date,1))}>›</button></div><button onClick={()=>changeDate(today)}>Today</button><label>Doctor<select value={doctor} onChange={event=>{setDoctor(event.target.value);setSelectedId(null);setMobileDoctor(null);resetSelectionState();}}><option value="">All doctors</option>{doctors.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Status<select value={status} onChange={event=>{setStatus(event.target.value);setSelectedId(null);resetSelectionState();}}><option value="">All statuses</option>{statuses.map(value=><option key={value} value={value}>{value==='no_show'?'No-show':value[0].toUpperCase()+value.slice(1)}</option>)}</select></label></div>
    <p className="calendar-note">Philippine time · Live clinic appointments.</p><p role="status">{message}</p>{error&&<p role="alert">{error}</p>}
    <div className="calendar-layout"><section className="calendar-panel"><h2>{formatBookingDate(date)}{date===today?' · Today':''}</h2>{loading?<p role="status">Loading appointments…</p>:<><p>{shown.length} appointments</p>{visibleDoctors.length>1&&<div className="calendar-doctor-pager"><button disabled={mobileIndex===0} onClick={()=>{setMobileDoctor(visibleDoctors[mobileIndex-1][0]);setSelectedId(null);resetSelectionState();}}>‹</button><span>{visibleDoctors[mobileIndex][1]}<small>Doctor {mobileIndex+1} of {visibleDoctors.length}</small></span><button disabled={mobileIndex===visibleDoctors.length-1} onClick={()=>{setMobileDoctor(visibleDoctors[mobileIndex+1][0]);setSelectedId(null);resetSelectionState();}}>›</button></div>}{!shown.length?<p className="calendar-empty">{appointments.length?'No appointments match these filters.':'No appointments for this date.'}</p>:<div className="calendar-doctors">{visibleDoctors.map(([id,name],index)=><section key={id} className={index===mobileIndex?'mobile-doctor-active':'mobile-doctor-hidden'}><h3>{name}</h3><ol>{shown.filter(item=>item.doctor_id===id).map(item=><li key={item.id}><button className="calendar-entry" aria-pressed={selectedId===item.id} onClick={()=>{setSelectedId(item.id);resetSelectionState();setMessage('');setError('');}}><time>{item.timeLabel}</time><strong>{item.patientName}</strong><span>{item.visitLabel}</span><span className="calendar-badges"><StatusBadge status={item.status}/>{item.priority==='urgent'&&<span className="badge calendar-urgent">Urgent</span>}</span><span className="calendar-view">View appointment →</span></button></li>)}</ol></section>)}</div>}</>}</section>
    <section className="calendar-panel calendar-details"><h2>Appointment information</h2>{!selected?<p>Select an appointment to view its operational details and available actions.</p>:<><h3>{selected.patientName}</h3><div className="calendar-badges"><StatusBadge status={selected.status}/>{selected.priority==='urgent'&&<span className="badge calendar-urgent">Urgent</span>}</div><dl><dt>Date / time</dt><dd>{formatBookingDate(selected.date)} · {selected.timeLabel}</dd><dt>Doctor</dt><dd>{selected.doctorName}</dd><dt>Visit / reason</dt><dd>{selected.visitLabel} · {selected.reason}</dd><dt>Appointment state</dt><dd>{arrivalLabel(selected)}</dd></dl><div className="calendar-actions">{actions.confirmArrival&&<button disabled={submitting} onClick={()=>update('arrival')}>{submitting?'Confirming…':'Confirm Arrival'}</button>}{(actions.noShow||actions.noShowGracePending)&&<button disabled={submitting||!actions.noShow} onClick={()=>setConfirmingNoShow(true)}>Mark No-show</button>}{actions.cancel&&!cancelling&&<button disabled={submitting} onClick={()=>setCancelling(true)}>Cancel Appointment</button>}{actions.queue&&<Link className="action-link" to="/staff/queue">View in Appointment Queue</Link>}</div>{actions.noShowGracePending&&<p role="status">Mark No-show becomes available at {clinicTime(actions.noShowAvailableAt)}—five minutes after the appointment start.</p>}{confirmingNoShow&&actions.noShow&&<div className="calendar-confirm"><p>Confirm this patient did not attend the scheduled appointment.</p><button disabled={submitting} onClick={()=>update('noShow')}>{submitting?'Saving…':'Confirm no-show'}</button><button disabled={submitting} onClick={()=>setConfirmingNoShow(false)}>Keep current status</button></div>}{cancelling&&actions.cancel&&<div className="calendar-cancel"><p>Cancel {selected.patientName}’s appointment?</p><button disabled={submitting} onClick={()=>update('cancelled')}>Yes, cancel appointment</button><button disabled={submitting} onClick={()=>setCancelling(false)}>Keep appointment</button></div>}{!actions.cancel&&!actions.confirmArrival&&!actions.noShow&&!actions.noShowGracePending&&!actions.queue&&<p>This appointment is view-only here.</p>}</>}</section></div>
  </div>;
}
