import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import FormField from '../../components/public/FormField.jsx';
import StatusBadge from '../../components/dashboard/StatusBadge.jsx';
import WalkInQueuePreview from '../../components/staff/WalkInQueuePreview.jsx';
import { clinicToday, formatBookingDate, formatEncounter, formatSlot } from '../../services/dateTimeService.js';
import { sameDayTimeOptions, staffApiErrorMessage, staffApiService, staffVisitTypes } from '../../services/staffApiService.js';
import '../../styles/staff-walkin.css';

export default function StaffWalkInAppointment(){const{id}=useParams();return <WalkInAppointment key={id} patientId={id}/>}
function WalkInAppointment({patientId}){
  const navigate=useNavigate(); const date=clinicToday(); const [state,setState]=useState({loading:true,patient:null,records:[],doctors:[],appointments:[],error:''}); const [values,setValues]=useState({doctor:'',service:'',time:'',reason:'',priority:'normal'}); const [saved,setSaved]=useState(null); const [submitting,setSubmitting]=useState(false); const [actionError,setActionError]=useState('');
  useEffect(()=>{Promise.all([staffApiService.getPatientContext(patientId),staffApiService.getDoctors(),staffApiService.getAppointments(date)]).then(([context,doctors,appointments])=>setState({loading:false,...context,doctors,appointments,error:''})).catch(error=>setState(old=>({...old,loading:false,error:staffApiErrorMessage(error,'Patient was not found.')})));},[patientId,date]);
  const slots=useMemo(()=>sameDayTimeOptions().filter(time=>!state.appointments.some(item=>item.doctor_id===values.doctor&&item.time===time&&!['cancelled','no_show'].includes(item.status))),[state.appointments,values.doctor]);
  async function submit(event){event.preventDefault();if(saved)return;setSubmitting(true);setActionError('');try{setSaved(await staffApiService.createWalkInAppointment(patientId,{...values,date}));}catch(error){setActionError(staffApiErrorMessage(error,'Unable to create the walk-in appointment.'));}finally{setSubmitting(false);}}
  async function checkIn(){setSubmitting(true);try{await staffApiService.checkIn(saved.id);navigate('/staff/queue');}catch(error){setActionError(staffApiErrorMessage(error,'Unable to check in this patient.'));setSubmitting(false);}}
  if(state.loading)return <div className="staff-walkin walkin-panel"><h1>Create Walk-in Appointment</h1><p role="status">Loading patient and Doctor information…</p></div>;
  if(state.error)return <div className="staff-walkin walkin-panel"><h1>Patient not found</h1><p role="alert">{state.error}</p><Link className="action-link" to="/staff/patients/new">Find or register a patient</Link></div>;
  const patient=state.patient;
  if(saved)return <div className="staff-walkin walkin-panel"><h1>Walk-in appointment created</h1><p role="status">{patient.full_name}’s confirmed appointment was saved by the clinic API.</p><StatusBadge status={saved.status}/><p>{formatBookingDate(date)} · {formatSlot(values.time)}</p><p>Ready for check-in. No portal account was created.</p>{actionError&&<p role="alert">{actionError}</p>}<div className="walkin-actions"><button disabled={submitting} onClick={checkIn}>{submitting?'Checking in…':'Check In and Open Queue'}</button><Link className="action-link" to="/staff/calendar">Full Calendar</Link><Link className="action-link" to="/staff/queue">Queue / Check-in</Link></div></div>;
  return <div className="staff-walkin"><Link to="/staff/patients/new">← Find or register a patient</Link><h1>Create Walk-in Appointment</h1><p>Same-day appointment · {formatBookingDate(date)} · Philippine time</p><div className="walkin-layout"><div><section className="walkin-panel"><h2>Patient information</h2><h3>{patient.full_name}</h3><p>{patient.dob} · {patient.sex} · {patient.contact_number}</p><p>Senior: {patient.isSenior?'Yes':'No'} (derived from DOB) · PWD: {patient.is_pwd?'Yes':'No'}</p><p>Using the selected patient’s existing ID. Patient information is read-only here.</p></section>
    <section className="walkin-panel"><h2>Consultation summaries</h2>{state.records.length?<ul className="walkin-queue">{state.records.map(record=><li key={record.id}><strong>{formatEncounter(record.encounter_at)}</strong><span>{record.attending_doctor}</span><span>{record.diagnosis_summary}</span></li>)}</ul>:<p>No consultation summaries available.</p>}<p>Detailed notes, prescriptions, and certificates are not available to Staff.</p></section>
    <form className="walkin-panel" onSubmit={submit}><h2>Visit details</h2>{actionError&&<p role="alert" className="walkin-error">{actionError}</p>}{!state.doctors.length&&<p role="status">No active doctors are available.</p>}<div className="walkin-fields"><FormField name="walkin-doctor" label="Doctor" value={values.doctor} onChange={event=>setValues({...values,doctor:event.target.value,time:''})}><option value="">Select an active doctor</option>{state.doctors.map(item=><option key={item.id} value={item.id}>{item.display_name}{item.specialty?` · ${item.specialty}`:''}</option>)}</FormField><FormField name="walkin-service" label="Visit type / service" value={values.service} onChange={event=>setValues({...values,service:event.target.value})}><option value="">Select visit type</option>{staffVisitTypes.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</FormField><FormField name="walkin-slot" label="Available same-day time" value={values.time} disabled={!values.doctor} onChange={event=>setValues({...values,time:event.target.value})}><option value="">Select time</option>{slots.map(time=><option key={time} value={time}>{formatSlot(time)}</option>)}</FormField><FormField name="walkin-priority" label="Appointment priority" value={values.priority} onChange={event=>setValues({...values,priority:event.target.value})}><option value="normal">Normal</option><option value="urgent">Urgent</option></FormField></div><label className="walkin-reason">Reason for visit<textarea required value={values.reason} onChange={event=>setValues({...values,reason:event.target.value})} rows={3}/></label><p>Senior/PWD queue priority is derived by the backend from patient information.</p><div className="walkin-actions"><Link className="action-link" to="/staff/patients/new">Cancel</Link><button type="submit" disabled={submitting||!state.doctors.length}>{submitting?'Creating…':'Create Walk-in Appointment'}</button></div></form></div><WalkInQueuePreview/></div></div>;
}
