import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import FormField from '../../components/public/FormField.jsx';
import StatusBadge from '../../components/dashboard/StatusBadge.jsx';
import { clinicToday, formatBookingDate, formatEncounter, formatSlot } from '../../services/dateTimeService.js';
import { staffApiErrorMessage, staffApiService, staffVisitTypes } from '../../services/staffApiService.js';
import '../../styles/staff-walkin.css';

export default function StaffWalkInAppointment(){const{id}=useParams();return <WalkInAppointment key={id} patientId={id}/>}
function WalkInAppointment({patientId}){
  const navigate=useNavigate(); const date=clinicToday(); const [state,setState]=useState({loading:true,patient:null,records:[],doctors:[],error:''}); const [values,setValues]=useState({doctor:'',service:'',time:'',reason:''}); const [slots,setSlots]=useState([]); const [loadingSlots,setLoadingSlots]=useState(false); const [saved,setSaved]=useState(null); const [submitting,setSubmitting]=useState(false); const [actionError,setActionError]=useState('');
  useEffect(()=>{Promise.all([staffApiService.getPatientContext(patientId),staffApiService.getDoctors()]).then(([context,doctors])=>setState({loading:false,...context,doctors,error:''})).catch(error=>setState(old=>({...old,loading:false,error:staffApiErrorMessage(error,'Patient was not found.')})));},[patientId]);
  useEffect(()=>{let active=true;if(!values.doctor){setSlots([]);setLoadingSlots(false);return()=>{active=false;};}setLoadingSlots(true);staffApiService.getAvailableSlots(values.doctor,date).then(items=>{if(active)setSlots(items);}).catch(error=>{if(active){setSlots([]);setActionError(staffApiErrorMessage(error,'Unable to load this Doctor’s same-day schedule.'));}}).finally(()=>{if(active)setLoadingSlots(false);});return()=>{active=false;};},[values.doctor,date]);
  async function submit(event){event.preventDefault();if(saved)return;setSubmitting(true);setActionError('');try{setSaved(await staffApiService.createWalkInAppointment(patientId,{...values,date}));}catch(error){setActionError(staffApiErrorMessage(error,'Unable to create the walk-in appointment.'));if(error?.status===409&&values.doctor){setValues(current=>({...current,time:''}));setSlots(await staffApiService.getAvailableSlots(values.doctor,date).catch(()=>[]));}}finally{setSubmitting(false);}}
  async function confirmArrival(){setSubmitting(true);try{await staffApiService.checkIn(saved.id);navigate('/staff/queue');}catch(error){setActionError(staffApiErrorMessage(error,'Unable to confirm arrival. Refresh and try again.'));setSubmitting(false);}}
  if(state.loading)return <div className="staff-walkin walkin-panel"><h1>Create Walk-in Appointment</h1><p role="status">Loading patient and Doctor information…</p></div>;
  if(state.error)return <div className="staff-walkin walkin-panel"><h1>Patient not found</h1><p role="alert">{state.error}</p><Link className="action-link" to="/staff/patients/new">Find or register a patient</Link></div>;
  const patient=state.patient;
  if(saved)return <div className="staff-walkin walkin-panel"><h1>Walk-in appointment created</h1><p role="status">{patient.full_name}’s confirmed appointment was saved by the clinic API.</p><StatusBadge status={saved.status}/><p>{formatBookingDate(date)} · {formatSlot(values.time)}</p><p>Ready to confirm arrival. No portal account was created.</p>{actionError&&<p role="alert">{actionError}</p>}<div className="walkin-actions"><button disabled={submitting} onClick={confirmArrival}>{submitting?'Confirming…':'Confirm Arrival and Open Queue'}</button><Link className="action-link" to="/staff/calendar">Full Calendar</Link><Link className="action-link" to="/staff/queue">Appointment Queue</Link></div></div>;
  return <div className="staff-walkin"><Link to="/staff/patients/new">← Find or register a patient</Link><h1>Create Walk-in Appointment</h1><p>Same-day appointment · {formatBookingDate(date)} · Philippine time</p><div className="walkin-layout"><div><section className="walkin-panel"><h2>Patient information</h2><h3>{patient.full_name}</h3><p>{patient.dob} · {patient.sex} · {patient.contact_number}</p><p>Senior: {patient.isSenior?'Yes':'No'} (derived from DOB) · PWD: {patient.is_pwd?'Yes':'No'}</p><p>Using the selected patient’s existing ID. Patient information is read-only here.</p></section>
    <section className="walkin-panel"><h2>Previous consultation dates</h2>{state.records.length?<ul className="walkin-queue">{state.records.slice(0,5).map(record=><li key={record.id}><strong>{formatEncounter(record.encounter_at)}</strong><span>{record.attending_doctor}</span></li>)}</ul>:<p>No previous consultations available.</p>}<p>Diagnoses, clinical notes, prescriptions, and certificates are not available to Staff.</p></section>
    <form className="walkin-panel" onSubmit={submit}><h2>Visit details</h2>{actionError&&<p role="alert" className="walkin-error">{actionError}</p>}{!state.doctors.length&&<p role="status">No active doctors are available.</p>}<div className="walkin-fields"><FormField name="walkin-doctor" label="Doctor" value={values.doctor} onChange={event=>{setActionError('');setValues({...values,doctor:event.target.value,time:''});}}><option value="">Select an active doctor</option>{state.doctors.map(item=><option key={item.id} value={item.id}>{item.display_name}{item.specialty?` · ${item.specialty}`:''}</option>)}</FormField><FormField name="walkin-service" label="Visit type / service" value={values.service} onChange={event=>setValues({...values,service:event.target.value})}><option value="">Select visit type</option>{staffVisitTypes.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</FormField><FormField name="walkin-slot" label="Available same-day time" value={values.time} disabled={!values.doctor||loadingSlots} onChange={event=>setValues({...values,time:event.target.value})}><option value="">{loadingSlots?'Loading times…':'Select time'}</option>{slots.map(slot=><option key={slot.time} value={slot.time} disabled={!slot.available}>{formatSlot(slot.time)}{!slot.available?' — Occupied':''}</option>)}</FormField></div><p className="walkin-slot-note">{!values.doctor?'Select a Doctor to view today’s published times.':loadingSlots?'Loading the Doctor’s schedule…':!slots.length?'This Doctor has no remaining published times today.':'Available times can be selected. Occupied times are shown but disabled.'}</p><label className="walkin-reason">Reason for visit<textarea required value={values.reason} onChange={event=>setValues({...values,reason:event.target.value})} rows={3}/></label><p>New walk-in appointments begin Normal. After Confirm Arrival, Staff may use the audited Mark Urgent action. Senior/PWD queue priority is derived by the backend.</p><div className="walkin-actions"><Link className="action-link" to="/staff/patients/new">Cancel</Link><button type="submit" disabled={submitting||!state.doctors.length||!slots.some(slot=>slot.time===values.time&&slot.available)}>{submitting?'Creating…':'Create Walk-in Appointment'}</button></div></form></div></div></div>;
}
