import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import FormField from '../../components/public/FormField.jsx';
import WalkInQueuePreview from '../../components/staff/WalkInQueuePreview.jsx';
import { staffApiErrorMessage, staffApiService } from '../../services/staffApiService.js';
import { ageFromDob, isSenior, profileSexOptions } from '../../services/patientProfileService.js';
import { clinicToday } from '../../services/dateTimeService.js';
import '../../styles/staff-walkin.css';

export default function StaffRegisterWalkIn(){
  const navigate=useNavigate(); const [query,setQuery]=useState(''); const [found,setFound]=useState([]); const [searching,setSearching]=useState(false); const [submitting,setSubmitting]=useState(false); const [values,setValues]=useState({full_name:'',dob:'',sex:'',contact_number:'',address:'',emergency_contact_name:'',emergency_contact_number:'',emergency_contact_relationship:'',allergies:'',is_pwd:false}); const [error,setError]=useState('');
  useEffect(()=>{if(!query.trim()){setFound([]);return;}const timer=setTimeout(async()=>{setSearching(true);try{setFound(await staffApiService.searchPatients(query));}catch(reason){setError(staffApiErrorMessage(reason,'Unable to search patients.'));}finally{setSearching(false);}},200);return()=>clearTimeout(timer);},[query]);
  function field(name,label,type='text',children){return <FormField name={'walkin-'+name} label={label} type={type} value={values[name]} onChange={event=>setValues({...values,[name]:event.target.value})} max={type==='date'?clinicToday():undefined}>{children}</FormField>}
  async function submit(event){event.preventDefault();setSubmitting(true);setError('');try{const patient=await staffApiService.registerWalkIn(values);navigate(`/staff/patients/${patient.id}/walk-in`);}catch(reason){setError(staffApiErrorMessage(reason,'Unable to register this walk-in patient.'));}finally{setSubmitting(false);}}
  const results=<ul className="walkin-results">{found.map(item=><li key={item.id}><div><strong>{item.full_name}</strong><p>{item.dob} · {item.contact_number}</p></div><Link className="action-link" to={`/staff/patients/${item.id}/walk-in`}>Select patient</Link></li>)}</ul>;
  return <div className="staff-walkin"><Link to="/staff/dashboard">← Back to Dashboard</Link><h1>Register Walk-in</h1><p>Find an existing patient first, or register a patient without a portal account.</p><div className="walkin-layout"><div><section className="walkin-panel"><h2>1. Find an existing patient</h2><FormField name="patient-search" label="Search by name or contact number" value={query} onChange={event=>setQuery(event.target.value)}/>{searching?<p role="status">Searching…</p>:query.trim()&&(found.length?results:<p role="status">No matching patient. Register below.</p>)}</section>
    <form className="walkin-panel" onSubmit={submit} noValidate><h2>2. New walk-in patient</h2><p>Fields marked * are required. No email, password, or portal account is created.</p>{error&&<p role="alert" className="walkin-error">{error}</p>}<div className="walkin-fields">{field('full_name','Full name *')}{field('dob','Date of birth *','date')}{field('sex','Sex *','text',<><option value="">Select sex</option>{profileSexOptions.map(value=><option key={value}>{value}</option>)}</>)}{field('contact_number','Contact number *','tel')}{field('address','Address (optional)')}{field('emergency_contact_name','Emergency contact name (optional)')}{field('emergency_contact_number','Emergency contact number (optional)','tel')}{field('emergency_contact_relationship','Emergency contact relationship (optional)')}{field('allergies','Allergies (optional, separated by commas)')}</div><label className="walkin-checkbox"><input type="checkbox" checked={values.is_pwd} onChange={event=>setValues({...values,is_pwd:event.target.checked})}/>Person with disability (PWD)</label><p>{ageFromDob(values.dob)===null?'Age and senior status will be derived from date of birth.':`Age: ${ageFromDob(values.dob)} · Senior status: ${isSenior(values.dob)?'Yes':'No'} (derived from date of birth)`}</p><div className="walkin-actions"><Link className="action-link" to="/staff/dashboard">Cancel</Link><button type="submit" disabled={submitting}>{submitting?'Registering…':'Register and continue'}</button></div></form></div><WalkInQueuePreview/></div></div>;
}
