import { appointmentRepository } from '../repositories/appointmentRepository.js';
import { patientRepository } from '../repositories/patientRepository.js';
import { doctorProfileService } from './doctorProfileService.js';
import { clinicToday, formatSlot } from './bookingService.js';
import { isSenior } from './patientProfileService.js';

export function queueTier(appointment, patient, date) { return appointment.priority === 'urgent' ? 0 : patient?.is_pwd || isSenior(patient?.dob, date) ? 1 : 2; }
export function compareQueue(a,b) { return a.tier-b.tier || new Date(a.check_in_at ?? a.appointment_at)-new Date(b.check_in_at ?? b.appointment_at) || a.id.localeCompare(b.id); }
function project(item,date) { const patient=patientRepository.get(item.patient_id), doctor=doctorProfileService.get(item.doctor_id), tier=queueTier(item,patient,date); return { id:item.id, patient_id:item.patient_id, patientName:patient?.full_name ?? 'Patient unavailable', doctor_id:item.doctor_id, doctor:doctor?.display_name ?? 'Doctor unavailable', appointment_at:item.appointment_at, timeLabel:formatSlot(item.appointment_at.slice(11,16)), status:item.status, check_in_at:item.check_in_at ?? null, priority:item.priority ?? 'normal', reason:item.reason, service:item.service, tier, priorityLabel:['Urgent','Senior / PWD','Normal'][tier], checkInLabel:item.check_in_at?'Checked in':'Not checked in' }; }
export const staffDashboardService = { getDashboard(now = new Date()) { const date=clinicToday(now); const appointments=appointmentRepository.list(now).filter(item=>item.appointment_at.slice(0,10)===date).map(item=>project(item,date)).sort((a,b)=>new Date(a.appointment_at)-new Date(b.appointment_at)); const waiting=appointments.filter(item=>item.check_in_at&&['pending','confirmed'].includes(item.status)).sort(compareQueue), upcoming=appointments.filter(item=>!item.check_in_at&&['pending','confirmed'].includes(item.status)); return structuredClone({date,appointments,waiting,upcoming,total:appointments.length,checkedIn:appointments.filter(item=>item.check_in_at).length,completed:appointments.filter(item=>item.status==='completed').length}); } };
