import assert from 'node:assert/strict';
import test from 'node:test';
import bcrypt from 'bcryptjs';
import { createApp } from '../src/app.js';
import { createAdminAccountModule } from '../src/services/adminAccountModule.js';
import { createTokenService } from '../src/services/tokenService.js';

const SECRET = 'admin-account-test-secret-12345678901234567';
const ids = { admin: '111111111111111111111111', doctorProfile: '222222222222222222222222', staffProfile: '333333333333333333333333', patientProfile: '444444444444444444444444', patientRole: '555555555555555555555555', doctor: 'aaaaaaaaaaaaaaaaaaaaaaaa', staff: 'bbbbbbbbbbbbbbbbbbbbbbbb', patient: 'cccccccccccccccccccccccc', guest: 'dddddddddddddddddddddddd' };
function clone(value) { return value == null ? value : structuredClone(value); }
function createContext() {
  const now = new Date('2026-09-25T00:00:00Z');
  const profiles = new Map([
    [ids.admin, { _id: ids.admin, user_profile_id: ids.admin, display_name: 'Admin', contact_number: '0900', role: 'admin', status: 'active', created_at: now, updated_at: now }],
    [ids.doctorProfile, { _id: ids.doctorProfile, user_profile_id: ids.doctorProfile, display_name: 'Existing Doctor', contact_number: '0911', role: 'doctor', status: 'active', created_at: now, updated_at: now }],
    [ids.staffProfile, { _id: ids.staffProfile, user_profile_id: ids.staffProfile, display_name: 'Existing Staff', contact_number: '0922', role: 'staff', status: 'active', created_at: now, updated_at: now }],
    [ids.patientProfile, { _id: ids.patientProfile, user_profile_id: ids.patientProfile, display_name: 'Portal Patient', contact_number: '0933', role: 'patient', status: 'active', created_at: now, updated_at: now }],
    [ids.patientRole, { _id: ids.patientRole, user_profile_id: ids.patientRole, display_name: 'Patient User', contact_number: '0944', role: 'patient', status: 'active', created_at: now, updated_at: now }],
  ]);
  const accounts = new Map([
    ['doctor@example.test', { _id: '900000000000000000000001', user_profile_id: ids.doctorProfile, email: 'doctor@example.test', password_hash: 'hash' }],
    ['staff@example.test', { _id: '900000000000000000000002', user_profile_id: ids.staffProfile, email: 'staff@example.test', password_hash: 'hash' }],
  ]);
  const doctors = new Map([[ids.doctor, { _id: ids.doctor, user_profile_id: ids.doctorProfile, specialty: 'General Medicine', license_number: 'LIC-OLD', ptr_number: 'PTR-OLD', signature_path: null, created_at: now, updated_at: now }]]);
  const staff = new Map([[ids.staff, { _id: ids.staff, user_profile_id: ids.staffProfile, created_at: now, updated_at: now }]]);
  const patients = new Map([
    [ids.patient, { _id: ids.patient, user_profile_id: ids.patientProfile, full_name: 'Portal Patient', contact_number: '0933', dob: new Date('1990-01-01'), sex: 'female', created_at: now, diagnosis: 'must not leak', notes: 'must not leak' }],
    [ids.guest, { _id: ids.guest, user_profile_id: null, full_name: 'Guest Walk-in', contact_number: '0955', dob: new Date('1985-01-01'), sex: 'male', created_at: now }],
  ]);
  let sequence = 50; const nextId = () => (++sequence).toString(16).padStart(24, '0');
  const profileObject = (profileId) => clone(profiles.get(String(profileId)));
  const accountEmail = (profileId) => [...accounts.values()].find((item) => item.user_profile_id === String(profileId))?.email ?? null;
  const doctorJoined = (item) => item ? { ...clone(item), user_profile_id: profileObject(item.user_profile_id), email: accountEmail(item.user_profile_id) } : null;
  const staffJoined = (item) => item ? { ...clone(item), user_profile_id: profileObject(item.user_profile_id), email: accountEmail(item.user_profile_id) } : null;
  const patientJoined = (item) => item ? { ...clone(item), user_profile_id: item.user_profile_id ? profileObject(item.user_profile_id) : null } : null;
  const repository = {
    async findAccountByEmail(email) { return clone(accounts.get(email)); },
    async createDoctorAccount(data) { if ([...doctors.values()].some((item) => item.license_number === data.license_number)) throw Object.assign(new Error('duplicate'), { code: 11000, keyPattern: { license_number: 1 } }); if ([...doctors.values()].some((item) => item.ptr_number === data.ptr_number)) throw Object.assign(new Error('duplicate'), { code: 11000, keyPattern: { ptr_number: 1 } }); const profile = { _id: nextId(), display_name: data.display_name, contact_number: data.contact_number, role: 'doctor', status: 'active', created_at: now, updated_at: now }; profiles.set(profile._id, profile); const account = { _id: nextId(), user_profile_id: profile._id, email: data.email, password_hash: data.password_hash }; accounts.set(account.email, account); const roleProfile = { _id: nextId(), user_profile_id: profile._id, specialty: data.specialty, license_number: data.license_number, ptr_number: data.ptr_number, signature_path: data.signature_path, created_at: now, updated_at: now }; doctors.set(roleProfile._id, roleProfile); return { profile: clone(profile), account: clone(account), roleProfile: clone(roleProfile) }; },
    async createStaffAccount(data) { const profile = { _id: nextId(), display_name: data.display_name, contact_number: data.contact_number, role: 'staff', status: 'active', created_at: now, updated_at: now }; profiles.set(profile._id, profile); const account = { _id: nextId(), user_profile_id: profile._id, email: data.email, password_hash: data.password_hash }; accounts.set(account.email, account); const roleProfile = { _id: nextId(), user_profile_id: profile._id, created_at: now, updated_at: now }; staff.set(roleProfile._id, roleProfile); return { profile: clone(profile), account: clone(account), roleProfile: clone(roleProfile) }; },
    async listDoctors({ search, page, limit }) { const items = [...doctors.values()].map(doctorJoined).filter((item) => !search || JSON.stringify(item).toLowerCase().includes(search.toLowerCase())); return { items: items.slice((page - 1) * limit, page * limit), total: items.length, page, limit }; },
    async findDoctorById(id) { return doctorJoined(doctors.get(String(id))); },
    async updateDoctor(id, profileUpdates, doctorUpdates) { const item = doctors.get(String(id)); if (!item) return null; Object.assign(profiles.get(item.user_profile_id), profileUpdates, { updated_at: new Date() }); Object.assign(item, doctorUpdates, { updated_at: new Date() }); return doctorJoined(item); },
    async setDoctorStatus(id, status) { const item = doctors.get(String(id)); if (!item) return null; profiles.get(item.user_profile_id).status = status; return doctorJoined(item); },
    async listStaff({ search, page, limit }) { const items = [...staff.values()].map(staffJoined).filter((item) => !search || JSON.stringify(item).toLowerCase().includes(search.toLowerCase())); return { items: items.slice((page - 1) * limit, page * limit), total: items.length, page, limit }; },
    async findStaffById(id) { return staffJoined(staff.get(String(id))); },
    async updateStaff(id, updates) { const item = staff.get(String(id)); if (!item) return null; Object.assign(profiles.get(item.user_profile_id), updates, { updated_at: new Date() }); return staffJoined(item); },
    async setStaffStatus(id, status) { const item = staff.get(String(id)); if (!item) return null; profiles.get(item.user_profile_id).status = status; return staffJoined(item); },
    async listPatients({ search, status, page, limit }) { let items = [...patients.values()].map(patientJoined).filter((item) => !search || `${item.full_name} ${item.contact_number}`.toLowerCase().includes(search.toLowerCase())); items = items.filter((item) => status === 'all' || (status === 'no_account' ? !item.user_profile_id : item.user_profile_id?.status === status)); return { items: items.slice((page - 1) * limit, page * limit), total: items.length, page, limit }; },
    async findPatientById(id) { return patientJoined(patients.get(String(id))); },
    async setPatientStatus(id, status) { const item = patients.get(String(id)); if (!item) return null; if (!item.user_profile_id) return { noAccount: true, patient: clone(item) }; profiles.get(item.user_profile_id).status = status; return patientJoined(item); },
  };
  const tokens = createTokenService(SECRET);
  const authModule = { tokens, service: { async getAuthenticatedUser(id) { const item = profiles.get(String(id)); if (!item) throw Object.assign(new Error('Authentication required'), { status: 401, code: 'UNAUTHENTICATED' }); return { user_profile_id: String(item._id), display_name: item.display_name, role: item.role, status: item.status }; } } };
  const adminAccountModule = createAdminAccountModule({ repository });
  const app = createApp({ nodeEnv: 'test', authSecret: SECRET, enableAuthorizationProbes: true }, { authModule, adminAccountModule });
  return { app, profiles, accounts, doctors, staff, patients, tokens, cookie: (profileId) => `arion_auth=${tokens.sign(profileId)}` };
}
async function withServer(app, callback) { const server = app.listen(0, '127.0.0.1'); await new Promise((resolve, reject) => { server.once('listening', resolve); server.once('error', reject); }); try { await callback(`http://127.0.0.1:${server.address().port}`); } finally { await new Promise((resolve) => server.close(resolve)); } }
function request(base, path, { method = 'GET', cookie, body } = {}) { return fetch(`${base}${path}`, { method, headers: { ...(cookie ? { cookie } : {}), ...(body ? { 'content-type': 'application/json' } : {}) }, body: body ? JSON.stringify(body) : undefined }); }
const doctorInput = { email: 'new-doctor@example.test', password: 'Temporary123!', display_name: 'New Doctor', contact_number: '09170000000', specialty: 'Family Medicine', license_number: 'LIC-NEW', ptr_number: 'PTR-NEW', signature_path: 'protected/new.png' };
const staffInput = { email: 'new-staff@example.test', password: 'Temporary123!', display_name: 'New Staff', contact_number: '09270000000' };

test('Admin provisions linked Doctor account with forced role and hashed password', async () => { const c = createContext(); await withServer(c.app, async (base) => { const response = await request(base, '/api/admin/doctors', { method: 'POST', cookie: c.cookie(ids.admin), body: doctorInput }); const body = await response.json(); assert.equal(response.status, 201); assert.equal(body.doctor.status, 'active'); const profile = c.profiles.get(body.doctor.user_profile_id); assert.equal(profile.role, 'doctor'); const account = c.accounts.get(doctorInput.email); assert.ok(account); assert.notEqual(account.password_hash, doctorInput.password); assert.equal(await bcrypt.compare(doctorInput.password, account.password_hash), true); assert.ok(c.doctors.has(body.doctor.id)); assert.equal('password_hash' in body.doctor, false); }); });
test('duplicate Doctor email, license and PTR return 409', async () => { for (const override of [{ email: 'doctor@example.test' }, { license_number: 'LIC-OLD' }, { ptr_number: 'PTR-OLD' }]) { const c = createContext(); await withServer(c.app, async (base) => assert.equal((await request(base, '/api/admin/doctors', { method: 'POST', cookie: c.cookie(ids.admin), body: { ...doctorInput, ...override } })).status, 409)); } });
for (const profile of [ids.patientRole, ids.doctorProfile, ids.staffProfile]) test(`${profile} cannot provision Doctor`, async () => { const c = createContext(); await withServer(c.app, async (base) => assert.equal((await request(base, '/api/admin/doctors', { method: 'POST', cookie: c.cookie(profile), body: doctorInput })).status, 403)); });
test('Admin lists, reads and updates only approved Doctor fields', async () => { const c = createContext(); await withServer(c.app, async (base) => { assert.equal((await request(base, '/api/admin/doctors?search=Existing', { cookie: c.cookie(ids.admin) })).status, 200); const updated = await request(base, `/api/admin/doctors/${ids.doctor}`, { method: 'PATCH', cookie: c.cookie(ids.admin), body: { display_name: 'Updated Doctor', specialty: 'Internal Medicine' } }); assert.equal(updated.status, 200); assert.equal((await updated.json()).doctor.display_name, 'Updated Doctor'); assert.equal((await request(base, `/api/admin/doctors/${ids.doctor}`, { method: 'PATCH', cookie: c.cookie(ids.admin), body: { role: 'admin' } })).status, 400); }); });
test('Doctor deactivate/reactivate preserves IDs and enforces active access', async () => { const c = createContext(); await withServer(c.app, async (base) => { const before = clone(c.doctors.get(ids.doctor)); const off = await request(base, `/api/admin/doctors/${ids.doctor}/deactivate`, { method: 'PATCH', cookie: c.cookie(ids.admin), body: {} }); assert.equal((await off.json()).doctor.status, 'inactive'); assert.equal((await request(base, '/api/authz-test/role/doctor', { cookie: c.cookie(ids.doctorProfile) })).status, 403); const on = await request(base, `/api/admin/doctors/${ids.doctor}/reactivate`, { method: 'PATCH', cookie: c.cookie(ids.admin), body: {} }); assert.equal((await on.json()).doctor.status, 'active'); assert.equal(c.doctors.get(ids.doctor)._id, before._id); assert.equal(c.doctors.get(ids.doctor).user_profile_id, before.user_profile_id); }); });

test('Admin provisions linked Staff account without username and with hashed password', async () => { const c = createContext(); await withServer(c.app, async (base) => { const response = await request(base, '/api/admin/staff', { method: 'POST', cookie: c.cookie(ids.admin), body: staffInput }); const body = await response.json(); assert.equal(response.status, 201); assert.equal(c.profiles.get(body.staff.user_profile_id).role, 'staff'); assert.equal('username' in body.staff, false); assert.equal(await bcrypt.compare(staffInput.password, c.accounts.get(staffInput.email).password_hash), true); }); });
test('duplicate Staff email is rejected and non-Admin cannot provision Staff', async () => { const c = createContext(); await withServer(c.app, async (base) => { assert.equal((await request(base, '/api/admin/staff', { method: 'POST', cookie: c.cookie(ids.admin), body: { ...staffInput, email: 'staff@example.test' } })).status, 409); assert.equal((await request(base, '/api/admin/staff', { method: 'POST', cookie: c.cookie(ids.staffProfile), body: staffInput })).status, 403); }); });
test('Admin lists, updates and preserves Staff through lifecycle', async () => { const c = createContext(); await withServer(c.app, async (base) => { assert.equal((await request(base, '/api/admin/staff?search=Existing', { cookie: c.cookie(ids.admin) })).status, 200); const update = await request(base, `/api/admin/staff/${ids.staff}`, { method: 'PATCH', cookie: c.cookie(ids.admin), body: { display_name: 'Updated Staff', contact_number: '0999' } }); assert.equal((await update.json()).staff.display_name, 'Updated Staff'); const before = clone(c.staff.get(ids.staff)); assert.equal((await request(base, `/api/admin/staff/${ids.staff}/deactivate`, { method: 'PATCH', cookie: c.cookie(ids.admin), body: {} })).status, 200); assert.equal((await request(base, '/api/authz-test/role/staff', { cookie: c.cookie(ids.staffProfile) })).status, 403); assert.equal((await request(base, `/api/admin/staff/${ids.staff}/reactivate`, { method: 'PATCH', cookie: c.cookie(ids.admin), body: {} })).status, 200); assert.equal(c.staff.get(ids.staff)._id, before._id); }); });

test('Admin Patient list supports search and account filters without clinical data', async () => { const c = createContext(); await withServer(c.app, async (base) => { for (const path of ['/api/admin/patients?search=Portal', '/api/admin/patients?search=0933', '/api/admin/patients?status=active', '/api/admin/patients?status=no_account']) { const response = await request(base, path, { cookie: c.cookie(ids.admin) }); assert.equal(response.status, 200); const serialized = JSON.stringify(await response.json()); for (const field of ['diagnosis', 'notes', 'prescriptions', 'certificates']) assert.ok(!serialized.includes(field)); } }); });
test('Patient portal lifecycle preserves Patient and UserProfile identity', async () => { const c = createContext(); await withServer(c.app, async (base) => { const before = clone(c.patients.get(ids.patient)); const off = await request(base, `/api/admin/patients/${ids.patient}/deactivate`, { method: 'PATCH', cookie: c.cookie(ids.admin), body: {} }); assert.equal((await off.json()).patient.account_status, 'inactive'); assert.equal((await request(base, '/api/authz-test/role/patient', { cookie: c.cookie(ids.patientProfile) })).status, 403); const on = await request(base, `/api/admin/patients/${ids.patient}/reactivate`, { method: 'PATCH', cookie: c.cookie(ids.admin), body: {} }); assert.equal((await on.json()).patient.account_status, 'active'); assert.equal(c.patients.get(ids.patient)._id, before._id); assert.equal(c.patients.get(ids.patient).user_profile_id, before.user_profile_id); }); });
test('walk-in Patient without portal account cannot be deactivated or reactivated', async () => { const c = createContext(); await withServer(c.app, async (base) => { for (const action of ['deactivate', 'reactivate']) { const response = await request(base, `/api/admin/patients/${ids.guest}/${action}`, { method: 'PATCH', cookie: c.cookie(ids.admin), body: {} }); assert.equal(response.status, 409); assert.equal((await response.json()).error.code, 'PATIENT_HAS_NO_PORTAL_ACCOUNT'); } }); });
test('no hard-delete or Admin clinical editing route exists', async () => { const c = createContext(); await withServer(c.app, async (base) => { for (const [method, path] of [['DELETE', `/api/admin/doctors/${ids.doctor}`], ['DELETE', `/api/admin/staff/${ids.staff}`], ['DELETE', `/api/admin/patients/${ids.patient}`]]) assert.equal((await request(base, path, { method, cookie: c.cookie(ids.admin) })).status, 404); assert.equal((await request(base, `/api/admin/patients/${ids.patient}`, { method: 'PATCH', cookie: c.cookie(ids.admin), body: { diagnosis: 'Changed' } })).status, 404); assert.equal((await request(base, '/api/doctor/appointments/100000000000000000000001/medical-record', { method: 'POST', cookie: c.cookie(ids.admin), body: { diagnosis: 'Changed' } })).status, 403); }); });
test('/api/health remains 200 with Admin account routes mounted', async () => { const c = createContext(); await withServer(c.app, async (base) => assert.equal((await request(base, '/api/health')).status, 200)); });
