import assert from 'node:assert/strict';
import test from 'node:test';
import { createApp } from '../src/app.js';
import { createPatientAppointmentModule } from '../src/services/patientAppointmentModule.js';
import { createSchedulingModule } from '../src/services/schedulingModule.js';
import { createSecurityLogger } from '../src/services/securityLogger.js';
import { createTokenService } from '../src/services/tokenService.js';

const SECRET = 'scheduling-test-secret-12345678901234567890';
const NOW = new Date('2026-09-24T00:00:00.000Z');
const ids = {
  doctorProfile: '411111111111111111111111', otherDoctorProfile: '422222222222222222222222',
  patientProfile: '433333333333333333333333', staffProfile: '444444444444444444444444', inactiveDoctorProfile: '455555555555555555555555', doctor: '511111111111111111111111',
  otherDoctor: '522222222222222222222222', patient: '611111111111111111111111',
  inactiveDoctor: '533333333333333333333333', recurring: '711111111111111111111111', otherRecurring: '722222222222222222222222',
};

function createContext({ clinic, securityEvents = [] } = {}) {
  const profiles = new Map([
    [ids.doctorProfile, { user_profile_id: ids.doctorProfile, display_name: 'Doctor One', role: 'doctor', status: 'active' }],
    [ids.otherDoctorProfile, { user_profile_id: ids.otherDoctorProfile, display_name: 'Doctor Two', role: 'doctor', status: 'active' }],
    [ids.patientProfile, { user_profile_id: ids.patientProfile, display_name: 'Patient One', role: 'patient', status: 'active' }],
    [ids.staffProfile, { user_profile_id: ids.staffProfile, display_name: 'Staff One', role: 'staff', status: 'active' }],
    [ids.inactiveDoctorProfile, { user_profile_id: ids.inactiveDoctorProfile, display_name: 'Inactive Doctor', role: 'doctor', status: 'inactive' }],
  ]);
  const doctors = [
    { _id: ids.doctor, user_profile_id: ids.doctorProfile },
    { _id: ids.otherDoctor, user_profile_id: ids.otherDoctorProfile },
    { _id: ids.inactiveDoctor, user_profile_id: ids.inactiveDoctorProfile },
  ];
  const patients = [{ _id: ids.patient, user_profile_id: ids.patientProfile, full_name: 'Patient One', dob: new Date('1990-01-01'), sex: 'other', contact_number: '09170000000', allergies: [], is_pwd: false }];
  const recurring = [
    { _id: ids.recurring, doctor_id: ids.doctor, day_of_week: 5, start_time: '09:00', end_time: '12:00', is_active: true },
    { _id: ids.otherRecurring, doctor_id: ids.otherDoctor, day_of_week: 5, start_time: '09:00', end_time: '12:00', is_active: true },
  ];
  const published = [];
  const blocked = [];
  const appointments = [];
  let sequence = 0x800;
  const nextId = () => (++sequence).toString(16).padStart(24, '0');
  const clone = (value) => structuredClone(value);
  const dateKey = (value) => new Date(value).toISOString().slice(0, 10);
  const overlap = (start, end, otherStart, otherEnd) => start < otherEnd && end > otherStart;

  const schedulingRepository = {
    async findDoctorByUserProfileId(profileId) { return clone(doctors.find((item) => item.user_profile_id === profileId) ?? null); },
    async findActiveDoctorById(doctorId) { const doctor = doctors.find((item) => item._id === doctorId); return doctor && profiles.get(doctor.user_profile_id)?.status === 'active' ? clone(doctor) : null; },
    async doctorExists(doctorId) { return doctors.some((item) => item._id === doctorId); },
    async listRecurring(doctorId) { return recurring.filter((item) => item.doctor_id === doctorId).map(clone); },
    async findRecurringOwned(id, doctorId) { return clone(recurring.find((item) => item._id === id && item.doctor_id === doctorId) ?? null); },
    async recurringOverlaps(doctorId, day, start, end, excludeId) { return recurring.some((item) => item.doctor_id === doctorId && item.day_of_week === day && item._id !== excludeId && overlap(start, end, item.start_time, item.end_time)); },
    async createRecurring(data) { const item = { _id: nextId(), ...data }; recurring.push(item); return clone(item); },
    async updateRecurringOwned(id, doctorId, changes) { const item = recurring.find((entry) => entry._id === id && entry.doctor_id === doctorId); if (!item) return null; Object.assign(item, changes); return clone(item); },
    async deleteRecurringOwned(id, doctorId) { const index = recurring.findIndex((item) => item._id === id && item.doctor_id === doctorId); return index < 0 ? null : clone(recurring.splice(index, 1)[0]); },
    async listPublished(doctorId) { return published.filter((item) => item.doctor_id === doctorId).map(clone); },
    async listPublishedActive(doctorId, earliestDate) { return published.filter((item) => item.doctor_id === doctorId && new Date(item.availability_date) >= earliestDate).map(clone); },
    async publishedOverlaps(doctorId, date, start, end) { return published.some((item) => item.doctor_id === doctorId && dateKey(item.availability_date) === dateKey(date) && overlap(start, end, item.start_time, item.end_time)); },
    async createPublished(data) { const item = { _id: nextId(), ...data }; published.push(item); return clone(item); },
    async deletePublishedOwned(id, doctorId) { const index = published.findIndex((item) => item._id === id && item.doctor_id === doctorId); return index < 0 ? null : clone(published.splice(index, 1)[0]); },
    async listPublishedForDate(doctorId, date) { return published.filter((item) => item.doctor_id === doctorId && dateKey(item.availability_date) === dateKey(date)).map(clone); },
    async listBlocked(doctorId) { return blocked.filter((item) => item.doctor_id === doctorId).map(clone); },
    async listBlockedActive(doctorId, current) { return blocked.filter((item) => item.doctor_id === doctorId && new Date(item.end_at) > current).map(clone); },
    async createBlocked(data) { const item = { _id: nextId(), ...data }; blocked.push(item); return clone(item); },
    async deleteBlockedOwned(id, doctorId) { const index = blocked.findIndex((item) => item._id === id && item.doctor_id === doctorId); return index < 0 ? null : clone(blocked.splice(index, 1)[0]); },
    async listBlocksOverlapping(doctorId, start, end) { return blocked.filter((item) => item.doctor_id === doctorId && new Date(item.start_at) < end && new Date(item.end_at) > start).map(clone); },
    async hasActiveAppointmentOverlap(doctorId, start, end) { return appointments.some((item) => item.doctor_id === doctorId && ['pending', 'confirmed', 'completed'].includes(item.status) && new Date(item.appointment_at) < end && new Date(item.appointment_at).getTime() + 1800000 > start.getTime()); },
    async listActiveAppointmentsBetween(doctorId, start, end) { return appointments.filter((item) => item.doctor_id === doctorId && ['pending', 'confirmed', 'completed'].includes(item.status) && new Date(item.appointment_at) >= start && new Date(item.appointment_at) < end).map(clone); },
  };
  const appointmentRepository = {
    async doctorExists(doctorId) { return schedulingRepository.doctorExists(doctorId); },
    async create(data) {
      if (appointments.some((item) => item.doctor_id === data.doctor_id && new Date(item.appointment_at).getTime() === data.appointment_at.getTime() && ['pending', 'confirmed', 'completed'].includes(item.status))) throw Object.assign(new Error('duplicate'), { code: 11000 });
      const item = { _id: nextId(), ...data };
      appointments.push(item);
      return clone(item);
    },
    async findOwnedById(id, patientId) { const item = appointments.find((entry) => entry._id === id && entry.patient_id === patientId); return item ? clone({ ...item, doctor_id: { _id: item.doctor_id, specialty: 'General', user_profile_id: { display_name: 'Doctor' } } }) : null; },
    async listByPatientId(patientId) { return appointments.filter((item) => item.patient_id === patientId).map(clone); },
    async findById(id) { return clone(appointments.find((item) => item._id === id) ?? null); },
    async cancelOwnedEligible() { return null; }, async confirmPending() { return null; },
  };
  const patientRepository = {
    async findByUserProfileId(profileId) { return clone(patients.find((item) => item.user_profile_id === profileId) ?? null); },
    async updateByUserProfileId() { return null; },
  };
  const schedulingModule = createSchedulingModule({ repository: schedulingRepository, clinic: clinic ?? { timeZone: 'Asia/Manila' }, now: () => new Date(NOW) });
  const patientAppointmentModule = createPatientAppointmentModule({ patients: patientRepository, appointments: appointmentRepository, bookingAvailabilityService: schedulingModule.bookingAvailabilityService, now: () => new Date(NOW) });
  const tokens = createTokenService(SECRET);
  const authService = { async getAuthenticatedUser(id) { const profile = profiles.get(String(id)); if (!profile) throw Object.assign(new Error('Authentication is required.'), { status: 401, code: 'UNAUTHENTICATED' }); return { ...profile }; }, async registerPatient() {}, async login() {} };
  const securityLogger = createSecurityLogger({ write(event) { securityEvents.push(event); } });
  const app = createApp({ nodeEnv: 'test', authSecret: SECRET }, { authModule: { service: authService, tokens }, schedulingModule, patientAppointmentModule, securityLogger });
  return { app, recurring, published, blocked, appointments, cookie: (profileId) => `arion_auth=${tokens.sign(profileId)}` };
}

async function withServer(app, check) { const server = app.listen(0, '127.0.0.1'); await new Promise((resolve, reject) => { server.once('listening', resolve); server.once('error', reject); }); try { await check(`http://127.0.0.1:${server.address().port}`); } finally { await new Promise((resolve) => server.close(resolve)); } }
function request(url, path, { method = 'GET', body, cookie } = {}) { return fetch(`${url}${path}`, { method, headers: { ...(body ? { 'content-type': 'application/json' } : {}), ...(cookie ? { cookie } : {}) }, body: body ? JSON.stringify(body) : undefined }); }
const staffPath = (doctorId, suffix) => `/api/staff/doctors/${doctorId}/${suffix}`;
const publish = (url, cookie, doctorId = ids.doctor) => request(url, staffPath(doctorId, 'published-availability'), { method: 'POST', cookie: cookie(ids.staffProfile), body: { availability_date: '2026-09-25', start_time: '09:00', end_time: '12:00' } });
const slots = (url, cookie, doctor = ids.doctor, date = '2026-09-25') => request(url, `/api/patient/doctors/${doctor}/available-slots?date=${date}`, { cookie: cookie(ids.patientProfile) });
const staffSlots = (url, cookie, doctor = ids.doctor, date = '2026-09-25', profile = ids.staffProfile) => request(url, `/api/staff/doctors/${doctor}/available-slots?date=${date}`, { cookie: profile ? cookie(profile) : undefined });
const booking = (doctor = ids.doctor, time = '09:00') => ({ doctor_id: doctor, appointment_at: `2026-09-25T${String(Number(time.slice(0,2))-8).padStart(2,'0')}:${time.slice(3)}:00.000Z`, visit_type: 'general_consultation', reason: 'General health concern' });

test('Doctor reads only own recurring availability', async () => { const { app, cookie } = createContext(); await withServer(app, async (url) => { const body = await (await request(url, '/api/doctor/availability', { cookie: cookie(ids.doctorProfile) })).json(); assert.deepEqual(body.availability.map((item) => item.id), [ids.recurring]); }); });
test('Doctor scheduling mutations are removed', async () => { const { app, cookie } = createContext(); await withServer(app, async (url) => assert.equal((await request(url, '/api/doctor/availability', { method: 'POST', cookie: cookie(ids.doctorProfile), body: { day_of_week: 5, start_time: '13:00', end_time: '17:00' } })).status, 404)); });
test('Doctor cannot create, update, or delete any scheduling resource', async () => { const { app, cookie } = createContext(); await withServer(app, async (url) => { const auth = cookie(ids.doctorProfile); const attempts = [request(url, `/api/doctor/availability/${ids.recurring}`, { method: 'PATCH', cookie: auth, body: { is_active: false } }), request(url, `/api/doctor/availability/${ids.recurring}`, { method: 'DELETE', cookie: auth }), request(url, '/api/doctor/published-availability', { method: 'POST', cookie: auth, body: { availability_date: '2026-09-25', start_time: '09:00', end_time: '12:00' } }), request(url, '/api/doctor/blocked-times', { method: 'POST', cookie: auth, body: { start_at: '2026-09-25T14:00:00+08:00', end_at: '2026-09-25T15:00:00+08:00', reason: 'No' } })]; assert.deepEqual((await Promise.all(attempts)).map(item => item.status), [404, 404, 404, 404]); }); });
test('Staff can create multiple non-overlapping ranges for an active Doctor', async () => { const { app, cookie } = createContext(); await withServer(app, async (url) => assert.equal((await request(url, staffPath(ids.doctor, 'availability'), { method: 'POST', cookie: cookie(ids.staffProfile), body: { day_of_week: 5, start_time: '13:00', end_time: '17:00' } })).status, 201)); });
test('Staff can update and disable a Doctor recurring range', async () => { const { app, cookie } = createContext(); await withServer(app, async (url) => { const response = await request(url, staffPath(ids.doctor, `availability/${ids.recurring}`), { method: 'PATCH', cookie: cookie(ids.staffProfile), body: { is_active: false } }); assert.equal(response.status, 200); assert.equal((await response.json()).availability.is_active, false); }); });
test('Staff schedule records remain scoped to the target Doctor', async () => { const { app, cookie, recurring } = createContext(); await withServer(app, async (url) => { assert.equal((await request(url, staffPath(ids.doctor, `availability/${ids.otherRecurring}`), { method: 'DELETE', cookie: cookie(ids.staffProfile) })).status, 404); assert.equal(recurring.some(item => item._id === ids.otherRecurring), true); assert.equal((await request(url, staffPath(ids.otherDoctor, `availability/${ids.otherRecurring}`), { method: 'DELETE', cookie: cookie(ids.staffProfile) })).status, 200); assert.equal(recurring.some(item => item._id === ids.otherRecurring), false); }); });
test('invalid recurring start greater than or equal to end is rejected', async () => { const { app, cookie } = createContext(); await withServer(app, async (url) => assert.equal((await request(url, staffPath(ids.doctor, 'availability'), { method: 'POST', cookie: cookie(ids.staffProfile), body: { day_of_week: 5, start_time: '12:00', end_time: '09:00' } })).status, 400)); });
test('Patient cannot use Staff scheduling routes', async () => { const { app, cookie } = createContext(); await withServer(app, async (url) => assert.equal((await request(url, staffPath(ids.doctor, 'availability'), { method: 'POST', cookie: cookie(ids.patientProfile), body: { day_of_week: 5, start_time: '13:00', end_time: '17:00' } })).status, 403)); });
test('Staff cannot manage an inactive Doctor schedule', async () => { const { app, cookie } = createContext(); await withServer(app, async (url) => assert.equal((await request(url, staffPath(ids.inactiveDoctor, 'availability'), { method: 'POST', cookie: cookie(ids.staffProfile), body: { day_of_week: 5, start_time: '13:00', end_time: '17:00' } })).status, 404)); });
test('Staff publishes a specific date within the recurring template', async () => { const { app, cookie } = createContext(); await withServer(app, async (url) => assert.equal((await publish(url, cookie)).status, 201)); });
test('publication beyond 30 days is rejected', async () => { const { app, cookie } = createContext(); await withServer(app, async (url) => assert.equal((await request(url, staffPath(ids.doctor, 'published-availability'), { method: 'POST', cookie: cookie(ids.staffProfile), body: { availability_date: '2026-10-25', start_time: '09:00', end_time: '12:00' } })).status, 400)); });
test('publication outside active recurring template is rejected', async () => { const { app, cookie } = createContext(); await withServer(app, async (url) => assert.equal((await request(url, staffPath(ids.doctor, 'published-availability'), { method: 'POST', cookie: cookie(ids.staffProfile), body: { availability_date: '2026-09-25', start_time: '13:00', end_time: '15:00' } })).status, 409)); });
test('overlapping published ranges are rejected', async () => { const { app, cookie } = createContext(); await withServer(app, async (url) => { assert.equal((await publish(url, cookie)).status, 201); assert.equal((await request(url, staffPath(ids.doctor, 'published-availability'), { method: 'POST', cookie: cookie(ids.staffProfile), body: { availability_date: '2026-09-25', start_time: '10:00', end_time: '11:00' } })).status, 409); }); });
test('Staff creates a partial-day block', async () => { const { app, cookie } = createContext(); await withServer(app, async (url) => assert.equal((await request(url, staffPath(ids.doctor, 'blocked-times'), { method: 'POST', cookie: cookie(ids.staffProfile), body: { start_at: '2026-09-25T09:30:00+08:00', end_at: '2026-09-25T10:30:00+08:00', reason: 'Meeting' } })).status, 201)); });
test('Staff creates a whole-day block using clinic-local day boundaries', async () => { const { app, cookie } = createContext(); await withServer(app, async (url) => assert.equal((await request(url, staffPath(ids.doctor, 'blocked-times'), { method: 'POST', cookie: cookie(ids.staffProfile), body: { start_at: '2026-09-25T00:00:00+08:00', end_at: '2026-09-26T00:00:00+08:00', reason: 'Leave' } })).status, 201)); });
test('blocked time overrides published slots', async () => { const { app, cookie } = createContext(); await withServer(app, async (url) => { await publish(url, cookie); await request(url, staffPath(ids.doctor, 'blocked-times'), { method: 'POST', cookie: cookie(ids.staffProfile), body: { start_at: '2026-09-25T09:30:00+08:00', end_at: '2026-09-25T10:30:00+08:00', reason: 'Meeting' } }); const body = await (await slots(url, cookie)).json(); assert.deepEqual(body.slots.map((item) => item.start_time), ['09:00','10:30','11:00','11:30']); }); });
test('booked appointment remains visible as an occupied non-selectable slot', async () => { const { app, cookie, appointments } = createContext(); appointments.push({ _id: '900000000000000000000001', patient_id: ids.patient, doctor_id: ids.doctor, appointment_at: new Date('2026-09-25T01:00:00.000Z'), status: 'confirmed' }); await withServer(app, async (url) => { await publish(url, cookie); const body = await (await slots(url, cookie)).json(); const occupied = body.slots.find((item) => item.start_time === '09:00'); assert.deepEqual({ available: occupied.available, occupied: occupied.occupied }, { available: false, occupied: true }); assert.equal('patient_id' in occupied, false); assert.equal(body.slots.find((item) => item.start_time === '09:30').available, true); }); });
test('Staff slot lookup returns published availability with occupied times disabled and remains Staff-only', async () => { const { app, cookie, appointments } = createContext(); appointments.push({ _id: '900000000000000000000003', patient_id: ids.patient, doctor_id: ids.doctor, appointment_at: new Date('2026-09-25T01:00:00.000Z'), status: 'confirmed' }); await withServer(app, async (url) => { await publish(url, cookie); const response = await staffSlots(url, cookie); const body = await response.json(); assert.equal(response.status, 200); const occupied = body.slots.find((item) => item.start_time === '09:00'); assert.deepEqual({ available: occupied.available, occupied: occupied.occupied }, { available: false, occupied: true }); assert.equal('patient_id' in occupied, false); assert.equal(body.slots.find((item) => item.start_time === '09:30').available, true); assert.equal((await staffSlots(url, cookie, ids.doctor, '2026-09-25', ids.patientProfile)).status, 403); assert.equal((await staffSlots(url, cookie, ids.doctor, '2026-09-25', ids.doctorProfile)).status, 403); assert.equal((await staffSlots(url, cookie, ids.doctor, '2026-09-25', null)).status, 401); }); });
test('unpublished recurring availability is not bookable', async () => { const { app, cookie } = createContext(); await withServer(app, async (url) => assert.deepEqual((await (await slots(url, cookie)).json()).slots, [])); });
test('Patient cannot see slots beyond 14 days', async () => { const { app, cookie } = createContext(); await withServer(app, async (url) => assert.deepEqual((await (await slots(url, cookie, ids.doctor, '2026-10-10')).json()).slots, [])); });
test('Patient cannot book an unpublished slot', async () => { const { app, cookie } = createContext(); await withServer(app, async (url) => assert.equal((await request(url, '/api/patient/appointments', { method: 'POST', cookie: cookie(ids.patientProfile), body: booking() })).status, 409)); });
test('Patient cannot book a blocked slot', async () => { const { app, cookie } = createContext(); await withServer(app, async (url) => { await publish(url, cookie); await request(url, staffPath(ids.doctor, 'blocked-times'), { method: 'POST', cookie: cookie(ids.staffProfile), body: { start_at: '2026-09-25T09:00:00+08:00', end_at: '2026-09-25T09:30:00+08:00', reason: 'Break' } }); assert.equal((await request(url, '/api/patient/appointments', { method: 'POST', cookie: cookie(ids.patientProfile), body: booking() })).status, 409); }); });
test('Patient cannot book an occupied slot', async () => { const { app, cookie, appointments } = createContext(); appointments.push({ _id: '900000000000000000000002', patient_id: ids.patient, doctor_id: ids.doctor, appointment_at: new Date('2026-09-25T01:00:00.000Z'), status: 'confirmed' }); await withServer(app, async (url) => { await publish(url, cookie); assert.equal((await request(url, '/api/patient/appointments', { method: 'POST', cookie: cookie(ids.patientProfile), body: booking() })).status, 409); }); });
test('Patient can book a valid explicitly published slot', async () => { const { app, cookie } = createContext(); await withServer(app, async (url) => { await publish(url, cookie); const response = await request(url, '/api/patient/appointments', { method: 'POST', cookie: cookie(ids.patientProfile), body: booking() }); assert.equal(response.status, 201); assert.equal((await response.json()).appointment.status, 'pending'); }); });
test('same Doctor cannot be double-booked', async () => { const { app, cookie } = createContext(); await withServer(app, async (url) => { await publish(url, cookie); assert.equal((await request(url, '/api/patient/appointments', { method: 'POST', cookie: cookie(ids.patientProfile), body: booking() })).status, 201); assert.equal((await request(url, '/api/patient/appointments', { method: 'POST', cookie: cookie(ids.patientProfile), body: booking() })).status, 409); }); });
test('different Doctors may be booked at the same time', async () => { const { app, cookie } = createContext(); await withServer(app, async (url) => { await publish(url, cookie); await publish(url, cookie, ids.otherDoctor); assert.equal((await request(url, '/api/patient/appointments', { method: 'POST', cookie: cookie(ids.patientProfile), body: booking(ids.doctor) })).status, 201); assert.equal((await request(url, '/api/patient/appointments', { method: 'POST', cookie: cookie(ids.patientProfile), body: booking(ids.otherDoctor) })).status, 201); }); });
test('past slot is rejected', async () => { const { app, cookie } = createContext(); await withServer(app, async (url) => assert.equal((await request(url, '/api/patient/appointments', { method: 'POST', cookie: cookie(ids.patientProfile), body: { ...booking(), appointment_at: '2026-09-23T01:00:00.000Z' } })).status, 400)); });
test('invalid 30-minute boundary is rejected', async () => { const { app, cookie } = createContext(); await withServer(app, async (url) => assert.equal((await request(url, '/api/patient/appointments', { method: 'POST', cookie: cookie(ids.patientProfile), body: { ...booking(), appointment_at: '2026-09-25T01:15:00.000Z' } })).status, 400)); });
test('availability deletion preserves existing appointments and overlapping blocks are rejected', async () => { const { app, cookie, appointments } = createContext(); await withServer(app, async (url) => { const publication = await (await publish(url, cookie)).json(); assert.equal((await request(url, '/api/patient/appointments', { method: 'POST', cookie: cookie(ids.patientProfile), body: booking() })).status, 201); assert.equal((await request(url, staffPath(ids.doctor, `published-availability/${publication.published_availability.id}`), { method: 'DELETE', cookie: cookie(ids.staffProfile) })).status, 200); assert.equal(appointments.length, 1); assert.equal((await request(url, staffPath(ids.doctor, 'blocked-times'), { method: 'POST', cookie: cookie(ids.staffProfile), body: { start_at: '2026-09-25T09:00:00+08:00', end_at: '2026-09-25T10:00:00+08:00', reason: 'Conflict' } })).status, 409); assert.equal(appointments.length, 1); }); });
test('configured clinic hours constrain recurring availability', async () => { const { app, cookie } = createContext({ clinic: { timeZone: 'Asia/Manila', openTime: '09:00', closeTime: '17:00' } }); await withServer(app, async (url) => assert.equal((await request(url, staffPath(ids.doctor, 'availability'), { method: 'POST', cookie: cookie(ids.staffProfile), body: { day_of_week: 6, start_time: '08:30', end_time: '10:00' } })).status, 400)); });
test('Staff schedule aggregate is target scoped and available only to Staff', async () => { const { app, cookie } = createContext(); await withServer(app, async (url) => { const response = await request(url, `/api/staff/doctors/${ids.doctor}/schedule`, { cookie: cookie(ids.staffProfile) }); assert.equal(response.status, 200); const schedule = (await response.json()).schedule; assert.equal(schedule.doctor_id, ids.doctor); assert.deepEqual(schedule.recurring_availability.map(item => item.id), [ids.recurring]); assert.equal((await request(url, `/api/staff/doctors/${ids.doctor}/schedule`, { cookie: cookie(ids.doctorProfile) })).status, 403); assert.equal((await request(url, `/api/staff/doctors/${ids.doctor}/schedule`)).status, 401); }); });
test('Staff scheduling rejects malformed IDs and protected fields', async () => { const { app, cookie } = createContext(); await withServer(app, async (url) => { assert.equal((await request(url, staffPath('not-an-id', 'availability'), { method: 'POST', cookie: cookie(ids.staffProfile), body: { day_of_week: 1, start_time: '09:00', end_time: '10:00' } })).status, 400); assert.equal((await request(url, staffPath(ids.doctor, 'availability'), { method: 'POST', cookie: cookie(ids.staffProfile), body: { doctor_id: ids.otherDoctor, day_of_week: 1, start_time: '09:00', end_time: '10:00' } })).status, 400); }); });
test('active schedule lists hide expired publications and blocks without deleting them', async () => { const { app, cookie, published, blocked } = createContext(); published.push({ _id: '811111111111111111111111', doctor_id: ids.doctor, availability_date: new Date('2026-09-23T00:00:00Z'), start_time: '09:00', end_time: '12:00' }, { _id: '822222222222222222222222', doctor_id: ids.doctor, availability_date: new Date('2026-09-24T00:00:00Z'), start_time: '07:00', end_time: '07:30' }, { _id: '833333333333333333333333', doctor_id: ids.doctor, availability_date: new Date('2026-09-24T00:00:00Z'), start_time: '08:00', end_time: '08:30' }); blocked.push({ _id: '844444444444444444444444', doctor_id: ids.doctor, start_at: new Date('2026-09-23T00:00:00Z'), end_at: new Date(NOW), reason: 'Expired' }, { _id: '855555555555555555555555', doctor_id: ids.doctor, start_at: new Date(NOW), end_at: new Date('2026-09-24T01:00:00Z'), reason: 'Current' }); await withServer(app, async (url) => { const schedule = (await (await request(url, `/api/staff/doctors/${ids.doctor}/schedule`, { cookie: cookie(ids.staffProfile) })).json()).schedule; assert.deepEqual(schedule.published_availability.map(item => item.id), ['833333333333333333333333']); assert.deepEqual(schedule.blocked_times.map(item => item.id), ['855555555555555555555555']); assert.equal(published.length, 3); assert.equal(blocked.length, 2); }); });
test('successful Staff scheduling mutation emits a safe structured event', async () => { const securityEvents = []; const { app, cookie } = createContext({ securityEvents }); await withServer(app, async (url) => { const response = await request(url, staffPath(ids.doctor, 'blocked-times'), { method: 'POST', cookie: cookie(ids.staffProfile), body: { start_at: '2026-09-25T14:00:00+08:00', end_at: '2026-09-25T15:00:00+08:00', reason: 'Sensitive schedule reason' } }); assert.equal(response.status, 201); const event = securityEvents.find(item => item.event === 'STAFF_SCHEDULE_CHANGE'); assert.equal(event.actor_user_profile_id, ids.staffProfile); assert.equal(event.target_id, ids.doctor); assert.equal(event.outcome, 'success'); assert.equal(event.metadata.action, 'blocked_time_created'); assert.equal(JSON.stringify(event).includes('Sensitive schedule reason'), false); assert.ok(event.timestamp); }); });
test('/api/health remains available with scheduling routes mounted', async () => { const { app } = createContext(); await withServer(app, async (url) => assert.equal((await request(url, '/api/health')).status, 200)); });
