import { useEffect, useState } from 'react';
import { Link, useLocation, useParams } from 'react-router-dom';
import RecordSection from '../../components/records/RecordSection.jsx';
import StatusBadge from '../../components/dashboard/StatusBadge.jsx';
import { doctorApiErrorMessage, doctorApiService } from '../../services/doctorApiService.js';
import { patientAge } from '../../services/patientApiService.js';
import { formatBookingDate } from '../../services/dateTimeService.js';
import '../../styles/doctor-record.css';

function Field({ label, name, value, onChange, error, required, type }) { const props = { id: name, name, value, onChange: event => onChange(event.target.value), required, 'aria-invalid': !!error, 'aria-describedby': error ? `${name}-error` : undefined }; return <div className="clinical-field"><label htmlFor={name}>{label}{required ? ' *' : ' (optional)'}</label>{type ? <input type={type} {...props} /> : <textarea rows={3} {...props} />}{error && <p id={`${name}-error`} className="field-error">{error}</p>}</div>; }

export default function DoctorAddRecord() {
  const { id } = useParams(); const { state: selection } = useLocation(); const [context, setContext] = useState(null); const [loadingError, setLoadingError] = useState(''); const [loading, setLoading] = useState(true);
  const [values, setValues] = useState({ diagnosis: '', notes: '', follow_up: '', prescriptions: [] }); const [errors, setErrors] = useState({}); const [saved, setSaved] = useState(null); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { let active = true; doctorApiService.getPatientContext(id, selection ?? {}).then((detail) => { if (!active) return; if (!detail) setLoadingError('Patient or appointment not found.'); else if (!detail.canAddRecord) setLoadingError(detail.consultationMessage); else setContext(detail); }).catch((error) => active && setLoadingError(doctorApiErrorMessage(error, 'Unable to load this consultation.'))).finally(() => active && setLoading(false)); return () => { active = false; }; }, [id, selection?.appointmentId]);
  const effectiveSelection = context ? { appointmentId: context.appointment.id, date: context.appointment.date } : selection; const back = <Link className="action-link" to={`/doctor/patients/${id}`} state={effectiveSelection}>Back to Patient Details</Link>; const update = (name, value) => setValues(previous => ({ ...previous, [name]: value }));
  async function submit(event) { event.preventDefault(); const nextErrors = {}; if (!values.diagnosis.trim()) nextErrors.diagnosis = 'Enter a diagnosis.'; values.prescriptions.forEach((row, index) => { if (!row.medicine.trim()) nextErrors[`medicine-${index}`] = 'Enter a medicine or remove this row.'; if (!row.dosage.trim()) nextErrors[`dosage-${index}`] = 'Enter a dosage.'; }); if (Object.keys(nextErrors).length) { setErrors(nextErrors); return; } setSubmitting(true); setErrors({}); try { setSaved(await doctorApiService.createMedicalRecord(context.appointment.id, values)); } catch (error) { setErrors({ form: doctorApiErrorMessage(error, 'Unable to save this medical record.') }); } finally { setSubmitting(false); } }
  if (loading) return <div className="doctor-record-page"><h1>Add Medical Record</h1><p role="status">Loading consultation…</p></div>;
  if (loadingError || !context) return <div className="doctor-record-page"><h1>Medical Record Unavailable</h1><RecordSection title="Unable to create a record"><p role="alert">{loadingError}</p>{back}<Link className="action-link" to="/doctor/schedule">Back to Schedule</Link></RecordSection></div>;
  if (saved) return <div className="doctor-record-page"><h1>Medical Record Saved</h1><RecordSection title="Consultation recorded"><p role="status">The medical record and {saved.prescriptions.length} prescription(s) were saved. The record is now read-only.</p><p><strong>{saved.diagnosis}</strong></p><div className="record-actions">{back}<Link className="action-link primary-action" to={`/doctor/records/${saved.id}/certificate/new`}>Issue Medical Certificate</Link></div></RecordSection></div>;
  return <div className="doctor-record-page"><h1>Add Medical Record</h1><p>Record the details of this consultation. Fields marked * are required.</p><div className="record-form-layout"><form onSubmit={submit} noValidate>{errors.form && <p role="alert" className="field-error">{errors.form}</p>}
    <RecordSection title="Consultation Details"><p>{formatBookingDate(context.appointment.date)} · {context.appointment.timeLabel} · Philippine time</p><p>{context.appointment.visitLabel} · {context.appointment.reason}</p><p>Encounter time is recorded by the server when saved.</p><StatusBadge status={context.appointment.status} /></RecordSection>
    <RecordSection title="Clinical Information">{[['diagnosis', 'Diagnosis'], ['notes', 'Doctor’s notes'], ['follow_up', 'Follow-up instructions']].map(([name, label]) => <Field key={name} name={name} label={label} value={values[name]} onChange={value => update(name, value)} required={name === 'diagnosis'} error={errors[name]} />)}</RecordSection>
    <RecordSection title="Prescriptions"><p>Optional. Add a row only when prescribing medicine.</p>{values.prescriptions.map((row, index) => <fieldset key={row.key}><legend>Prescription {index + 1}</legend>{[['medicine', 'Medicine'], ['dosage', 'Dosage'], ['instructions', 'Instructions']].map(([name, label]) => <Field key={name} type="text" name={`${name}-${index}`} label={label} required={name !== 'instructions'} value={row[name]} error={errors[`${name}-${index}`]} onChange={value => update('prescriptions', values.prescriptions.map(item => item.key === row.key ? { ...item, [name]: value } : item))} />)}<button type="button" className="action-link" onClick={() => update('prescriptions', values.prescriptions.filter(item => item.key !== row.key))}>Remove Prescription {index + 1}</button></fieldset>)}<button type="button" className="action-link" onClick={() => update('prescriptions', [...values.prescriptions, { key: crypto.randomUUID(), medicine: '', dosage: '', instructions: '' }])}>Add Prescription</button></RecordSection>
    <div className="record-actions"><Link className="action-link" to={`/doctor/patients/${id}`} state={effectiveSelection}>Cancel</Link><button disabled={submitting} type="submit" className="action-link primary-action">{submitting ? 'Saving…' : 'Save Medical Record'}</button></div></form>
    <aside><RecordSection title="Patient Information"><h3>{context.patient.full_name}</h3><p>{patientAge(context.patient.dob) ?? 'Age unavailable'} years old · {context.patient.sex}</p><p>{context.patient.contact_number}</p><p>Allergies: {context.patient.allergies?.join(', ') || 'None reported'}</p><p>{context.patient.is_pwd ? 'PWD' : 'Not a PWD'}</p></RecordSection></aside></div></div>;
}
