import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { ApiError } from '../src/services/apiClient.js';
import { createStaffApiRepository } from '../src/repositories/staffApiRepository.js';
import { createStaffApiService, patientListPage, staffApiErrorMessage, staffCalendarActions, staffQueueActions, urgentReasonOptions } from '../src/services/staffApiService.js';

const patient={id:'p1',full_name:'Alex Patient',contact_number:'0917',dob:'1990-01-15',age:36,sex:'male',is_pwd:false,is_senior:false,has_portal_account:true};
const doctor={id:'d1',display_name:'Dr. Maria Santos',specialty:'General Medicine'};
const appointment={id:'a1',patient,doctor,appointment_at:'2026-09-25T02:00:00.000Z',check_in_at:null,status:'confirmed',visit_type:'general_consultation',reason:'Headache',priority:'normal'};
const queue=[{...appointment,id:undefined,appointment_id:'urgent',check_in_at:'2026-09-25T01:55:00.000Z',queue_tier:0,queue_priority:'urgent'},{...appointment,id:undefined,appointment_id:'normal',check_in_at:'2026-09-25T01:50:00.000Z',queue_tier:2,queue_priority:'normal'}];

test('Staff repository uses approved live routes and never supplies created_by',async()=>{const calls=[];const client={async request(path,options={}){calls.push([path,options]);if(path.startsWith('/api/staff/appointments?'))return{appointments:[appointment]};if(path==='/api/staff/doctors')return{doctors:[doctor]};if(path.startsWith('/api/staff/patients?'))return{patients:[patient]};if(path==='/api/staff/patients/p1')return{patient};if(path.endsWith('/record-summary'))return{medical_record_summaries:[]};if(path.endsWith('/priority-history'))return{priority_history:[]};if(path==='/api/staff/patients/walk-in')return{patient};if(path.endsWith('/walk-in-appointments'))return{appointment};if(path==='/api/staff/queue')return{queue};if(path.endsWith('/check-in'))return{queue_entry:queue[0]};return{appointment};}};const repository=createStaffApiRepository(client);await repository.getAppointments('2026-09-25');await repository.getDoctors();await repository.searchPatients('Alex');await repository.getPatient('p1');await repository.getRecordSummary('p1');await repository.registerWalkIn(patient);await repository.createWalkInAppointment('p1',{doctor_id:'d1'});await repository.getQueue();await repository.confirmAppointment('a1');await repository.checkIn('a1');await repository.updatePriority('a1',{priority:'urgent',urgency_reason:'Severe pain or discomfort'});await repository.getPriorityHistory('a1');await repository.markNoShow('a1');await repository.cancelAppointment('a1');assert(calls.some(([path])=>path==='/api/staff/appointments?date=2026-09-25'));assert(calls.some(([path])=>path==='/api/staff/doctors'));assert(calls.some(([path])=>path==='/api/staff/appointments/a1/priority-history'));assert(calls.every(([,options])=>!options.body||!('created_by'in options.body)));});

test('Staff service preserves backend queue order and uses restricted summaries',async()=>{let queueReads=0;const repository={async getAppointments(){return[appointment]},async getQueue(){queueReads++;return queue},async getPatient(){return patient},async getRecordSummary(){return[{id:'r1',patient_name:'Alex Patient',encounter_at:'2026-09-20T02:00:00Z',attending_doctor:'Dr. Maria Santos',diagnosis_summary:'Migraine'}]},async searchPatients(){return[patient]}};const service=createStaffApiService(repository);assert.deepEqual((await service.getQueue()).map(item=>item.id),['urgent','normal']);const context=await service.getPatientContext('p1');assert.deepEqual(Object.keys(context.records[0]).sort(),['attending_doctor','diagnosis_summary','encounter_at','id','patient_name']);assert.equal(JSON.stringify(context).includes('prescriptions'),false);await service.getDashboard();assert.equal(queueReads,2);assert.equal(patientListPage(Array(11).fill(patient).map((item,index)=>({...item,id:String(index)})),2).items.length,5);});

test('Confirm Arrival is offered only for current-day pending or confirmed unchecked appointments',()=>{const today='2026-09-25';const now=new Date('2026-09-25T02:00:00.000Z');for(const status of ['pending','confirmed']){const item={...appointment,date:today,status};assert.equal(staffCalendarActions(item,today).confirmArrival,true);assert.equal(staffQueueActions(item,now).confirmArrival,true);}for(const item of [{...appointment,date:today,status:'cancelled'},{...appointment,date:today,status:'completed'},{...appointment,date:today,status:'no_show'},{...appointment,date:today,check_in_at:'2026-09-25T01:45:00.000Z'},{...appointment,date:'2026-09-26'}]){assert.equal(staffCalendarActions(item,today).confirmArrival,false);assert.equal(staffQueueActions(item,now).confirmArrival,false);}});

test('No-show UI eligibility begins exactly five minutes after the appointment start',()=>{const item={...appointment,date:'2026-09-25',appointment_at:'2026-09-25T02:00:00.000Z'};for(const now of ['2026-09-25T01:59:59.000Z','2026-09-25T02:00:00.000Z','2026-09-25T02:04:59.000Z']){for(const actions of [staffQueueActions(item,new Date(now)),staffCalendarActions(item,item.date,new Date(now))]){assert.equal(actions.noShow,false);assert.equal(actions.noShowGracePending,true);assert.equal(actions.noShowAvailableAt,new Date('2026-09-25T02:05:00.000Z').getTime());}}for(const now of ['2026-09-25T02:05:00.000Z','2026-09-25T02:06:00.000Z']){for(const actions of [staffQueueActions(item,new Date(now)),staffCalendarActions(item,item.date,new Date(now))]){assert.equal(actions.noShow,true);assert.equal(actions.noShowGracePending,false);}}for(const actions of [staffQueueActions({...item,check_in_at:'2026-09-25T02:01:00.000Z'},new Date('2026-09-25T02:06:00.000Z')),staffCalendarActions({...item,check_in_at:'2026-09-25T02:01:00.000Z'},item.date,new Date('2026-09-25T02:06:00.000Z'))]){assert.equal(actions.noShow,false);assert.equal(actions.noShowGracePending,false);}});

test('terminal appointments expose no arrival, No-show, queue-priority, or active-queue actions',()=>{const now=new Date('2026-09-25T02:10:00.000Z');for(const status of ['completed','cancelled','no_show']){const item={...appointment,date:'2026-09-25',status};const calendar=staffCalendarActions(item,item.date,now);const queueActions=staffQueueActions(item,now);assert.equal(calendar.confirmArrival,false);assert.equal(calendar.noShow,false);assert.equal(calendar.noShowGracePending,false);assert.equal(calendar.queue,false);assert.equal(queueActions.confirmArrival,false);assert.equal(queueActions.noShow,false);assert.equal(queueActions.noShowGracePending,false);assert.equal(queueActions.markUrgent,false);assert.equal(queueActions.setNormal,false);}});

test('Urgent controls require checked-in confirmed appointments and expose exact approved reasons',()=>{assert.deepEqual(urgentReasonOptions,['Sudden worsening of condition','Severe pain or discomfort','Breathing difficulty or respiratory concern','Dizziness, weakness, or risk of fainting','Active bleeding or recent injury','Doctor-directed priority','Other urgent concern']);const now=new Date('2026-09-25T02:10:00Z');const checked={...appointment,date:'2026-09-25',check_in_at:'2026-09-25T02:01:00Z'};assert.equal(staffQueueActions(checked,now).markUrgent,true);assert.equal(staffQueueActions({...checked,priority:'urgent'},now).setNormal,true);for(const item of [{...checked,status:'pending'},{...checked,status:'cancelled'},{...checked,check_in_at:null}]){assert.equal(staffQueueActions(item,now).markUrgent,false);assert.equal(staffQueueActions(item,now).setNormal,false);}});

test('Staff API errors expose safe business messages',()=>{assert.equal(staffApiErrorMessage(new ApiError('An existing Patient may match this person.',{status:409,code:'PATIENT_MATCH_FOUND'})),'An existing Patient may match this person.');});

test('all Staff pages use live API services with no Staff mock fallback or completion action',async()=>{for(const file of ['StaffDashboard.jsx','StaffCalendar.jsx','StaffQueue.jsx','StaffPatients.jsx','StaffRegisterWalkIn.jsx','StaffWalkInAppointment.jsx']){const source=await readFile(new URL(`../src/pages/staff/${file}`,import.meta.url),'utf8');assert.match(source,/staffApiService/);assert.doesNotMatch(source,/staffDashboardService|staffCalendarService|staffQueueService|staffPatientsService|staffWalkInService|Mock session|mock appointments/i);assert.doesNotMatch(source,/completeAppointment|Mark as Completed/);}});

test('routine Staff arrival UI uses one disabled-while-submitting action and no standalone confirmation request',async()=>{for(const file of ['StaffCalendar.jsx','StaffQueue.jsx']){const source=await readFile(new URL(`../src/pages/staff/${file}`,import.meta.url),'utf8');assert.match(source,/Confirm Arrival/);assert.match(source,/disabled=\{submitting\}/);assert.match(source,/staffApiService\.checkIn/);assert.doesNotMatch(source,/staffApiService\.confirm\(/);assert.doesNotMatch(source,/Confirm Appointment/);}});

test('Staff Queue explains and refreshes five-minute No-show eligibility',async()=>{const source=await readFile(new URL('../src/pages/staff/StaffQueue.jsx',import.meta.url),'utf8');assert.match(source,/five minutes after the appointment start/);assert.match(source,/disabled=\{submitting\|\|!actions\.noShow\}/);assert.match(source,/setInterval\(\(\)=>setCurrentTime\(new Date\(\)\),1000\)/);});

test('Staff Calendar represents scheduled, arrived, terminal, urgent, and No-show states without routine confirmation',async()=>{const source=await readFile(new URL('../src/pages/staff/StaffCalendar.jsx',import.meta.url),'utf8');assert.match(source,/Scheduled \/ Pending/);assert.match(source,/Arrived \/ Confirmed/);assert.match(source,/calendar-urgent/);assert.match(source,/Mark No-show becomes available/);assert.match(source,/View in Appointment Queue/);assert.match(source,/staffApiService\.checkIn/);assert.match(source,/staffApiService\.noShow/);assert.doesNotMatch(source,/Confirm Appointment|Not checked in/);});

test('Staff Queue clearly separates active, scheduled, and terminal appointments',async()=>{const source=await readFile(new URL('../src/pages/staff/StaffQueue.jsx',import.meta.url),'utf8');assert.match(source,/<h1>Appointment Queue<\/h1>/);assert.match(source,/View arrived patients and manage queue priority/);assert.match(source,/section\('Active Queue'/);assert.match(source,/section\('Scheduled \/ Not Yet Arrived'/);assert.match(source,/section\('Completed \/ Cancelled \/ No-show'/);assert.match(source,/\['Active Queue'/);assert.match(source,/\['Scheduled Today'/);assert.match(source,/\['Urgent'/);assert.match(source,/\['Completed Today'/);assert.doesNotMatch(source,/Queue \/ Check-in|Not checked in/);});

test('Staff Queue requires Urgent and correction reasons and displays audit history',async()=>{const source=await readFile(new URL('../src/pages/staff/StaffQueue.jsx',import.meta.url),'utf8');assert.match(source,/Mark Urgent/);assert.match(source,/Urgent reason/);assert.match(source,/Other urgent concern/);assert.match(source,/Correction reason/);assert.match(source,/priorityHistory/);assert.match(source,/disabled=\{submitting\|\|!priorityReady\}/);});

test('walk-in UI cannot assign Urgent before Confirm Arrival',async()=>{const source=await readFile(new URL('../src/pages/staff/StaffWalkInAppointment.jsx',import.meta.url),'utf8');assert.doesNotMatch(source,/walkin-priority/);assert.match(source,/begin Normal/);assert.match(source,/audited Mark Urgent action/);});

test('Patient, Doctor, Staff, and Admin portals use live API services',async()=>{const patientPage=await readFile(new URL('../src/pages/patient/PatientDashboard.jsx',import.meta.url),'utf8');const doctorPage=await readFile(new URL('../src/pages/doctor/DoctorDashboard.jsx',import.meta.url),'utf8');const adminPage=await readFile(new URL('../src/pages/admin/ManageDoctors.jsx',import.meta.url),'utf8');assert.match(patientPage,/patientApiService/);assert.match(doctorPage,/doctorApiService/);assert.match(adminPage,/adminApiService/);assert.doesNotMatch(adminPage,/adminDoctorService/);});
