import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { ApiError } from '../src/services/apiClient.js';
import { createStaffApiRepository } from '../src/repositories/staffApiRepository.js';
import { createStaffApiService, patientListPage, staffApiErrorMessage } from '../src/services/staffApiService.js';

const patient={id:'p1',full_name:'Alex Patient',contact_number:'0917',dob:'1990-01-15',age:36,sex:'male',is_pwd:false,is_senior:false,has_portal_account:true};
const doctor={id:'d1',display_name:'Dr. Maria Santos',specialty:'General Medicine'};
const appointment={id:'a1',patient,doctor,appointment_at:'2026-09-25T02:00:00.000Z',check_in_at:null,status:'confirmed',visit_type:'general_consultation',reason:'Headache',priority:'normal'};
const queue=[{...appointment,id:'urgent',check_in_at:'2026-09-25T01:55:00.000Z',queue_tier:0,queue_priority:'urgent'},{...appointment,id:'normal',check_in_at:'2026-09-25T01:50:00.000Z',queue_tier:2,queue_priority:'normal'}];

test('Staff repository uses approved live routes and never supplies created_by',async()=>{const calls=[];const client={async request(path,options={}){calls.push([path,options]);if(path.startsWith('/api/staff/appointments?'))return{appointments:[appointment]};if(path==='/api/staff/doctors')return{doctors:[doctor]};if(path.startsWith('/api/staff/patients?'))return{patients:[patient]};if(path==='/api/staff/patients/p1')return{patient};if(path.endsWith('/record-summary'))return{medical_record_summaries:[]};if(path==='/api/staff/patients/walk-in')return{patient};if(path.endsWith('/walk-in-appointments'))return{appointment};if(path==='/api/staff/queue')return{queue};if(path.endsWith('/check-in'))return{queue_entry:queue[0]};return{appointment};}};const repository=createStaffApiRepository(client);await repository.getAppointments('2026-09-25');await repository.getDoctors();await repository.searchPatients('Alex');await repository.getPatient('p1');await repository.getRecordSummary('p1');await repository.registerWalkIn(patient);await repository.createWalkInAppointment('p1',{doctor_id:'d1'});await repository.getQueue();await repository.confirmAppointment('a1');await repository.checkIn('a1');await repository.updatePriority('a1','urgent');await repository.markNoShow('a1');await repository.cancelAppointment('a1');assert(calls.some(([path])=>path==='/api/staff/appointments?date=2026-09-25'));assert(calls.some(([path])=>path==='/api/staff/doctors'));assert(calls.every(([,options])=>!options.body||!('created_by'in options.body)));});

test('Staff service preserves backend queue order and uses restricted summaries',async()=>{let queueReads=0;const repository={async getAppointments(){return[appointment]},async getQueue(){queueReads++;return queue},async getPatient(){return patient},async getRecordSummary(){return[{id:'r1',patient_name:'Alex Patient',encounter_at:'2026-09-20T02:00:00Z',attending_doctor:'Dr. Maria Santos',diagnosis_summary:'Migraine'}]},async searchPatients(){return[patient]}};const service=createStaffApiService(repository);assert.deepEqual((await service.getQueue()).map(item=>item.id),['urgent','normal']);const context=await service.getPatientContext('p1');assert.deepEqual(Object.keys(context.records[0]).sort(),['attending_doctor','diagnosis_summary','encounter_at','id','patient_name']);assert.equal(JSON.stringify(context).includes('prescriptions'),false);await service.getDashboard();assert.equal(queueReads,2);assert.equal(patientListPage(Array(11).fill(patient).map((item,index)=>({...item,id:String(index)})),2).items.length,5);});

test('Staff API errors expose safe business messages',()=>{assert.equal(staffApiErrorMessage(new ApiError('An existing Patient may match this person.',{status:409,code:'PATIENT_MATCH_FOUND'})),'An existing Patient may match this person.');});

test('all Staff pages use live API services with no Staff mock fallback or completion action',async()=>{for(const file of ['StaffDashboard.jsx','StaffCalendar.jsx','StaffQueue.jsx','StaffPatients.jsx','StaffRegisterWalkIn.jsx','StaffWalkInAppointment.jsx']){const source=await readFile(new URL(`../src/pages/staff/${file}`,import.meta.url),'utf8');assert.match(source,/staffApiService/);assert.doesNotMatch(source,/staffDashboardService|staffCalendarService|staffQueueService|staffPatientsService|staffWalkInService|Mock session|mock appointments/i);assert.doesNotMatch(source,/completeAppointment|Mark as Completed/);}});

test('Patient and Doctor stay live while Admin remains mock-backed',async()=>{const patientPage=await readFile(new URL('../src/pages/patient/PatientDashboard.jsx',import.meta.url),'utf8');const doctorPage=await readFile(new URL('../src/pages/doctor/DoctorDashboard.jsx',import.meta.url),'utf8');const adminPage=await readFile(new URL('../src/pages/admin/ManageDoctors.jsx',import.meta.url),'utf8');assert.match(patientPage,/patientApiService/);assert.match(doctorPage,/doctorApiService/);assert.match(adminPage,/adminDoctorService/);});
