import { useEffect, useRef, useState } from 'react';
import FormField from '../../components/public/FormField.jsx';
import { adminApiErrorMessage, adminApiService } from '../../services/adminApiService.js';
import '../../styles/admin-doctors.css';

const emptyForm = { email: '', password: '', display_name: '', contact_number: '' };
function Status({ value }) { return <span className={`account-status account-status-${value}`}>{value}</span>; }
function formFor(account) { return account ? { ...emptyForm, display_name: account.display_name ?? '', contact_number: account.contact_number ?? '', email: account.email ?? '' } : { ...emptyForm }; }

export default function ManageStaff() {
  const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [reload, setReload] = useState(0);
  const [list, setList] = useState({ loading: true, items: [], total: 0, page: 1, pageCount: 1, error: '' });
  const [panel, setPanel] = useState(null); const [form, setForm] = useState(emptyForm); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false); const heading = useRef(null);
  useEffect(() => { let active = true; const timer = setTimeout(async () => { setList(current => ({ ...current, loading: true, error: '' })); try { const result = await adminApiService.listStaff({ search, page, limit: 5 }); if (active) setList({ loading: false, ...result, error: '' }); } catch (failure) { if (active) setList({ loading: false, items: [], total: 0, page: 1, pageCount: 1, error: adminApiErrorMessage(failure, 'Unable to load Staff accounts.') }); } }, 200); return () => { active = false; clearTimeout(timer); }; }, [search, page, reload]);
  function open(mode, account = null) { setPanel({ mode, account }); setForm(formFor(account)); setError(''); setMessage(''); requestAnimationFrame(() => heading.current?.focus()); }
  async function save(event) { event.preventDefault(); if (saving || !panel || panel.mode === 'view') return; setSaving(true); setError(''); try { const account = panel.mode === 'add' ? await adminApiService.createStaff(form) : await adminApiService.updateStaff(panel.account.id, form); setForm(current => ({ ...current, password: '' })); setPanel({ mode: 'view', account }); setSearch(''); setPage(1); setReload(value => value + 1); setMessage(`Staff account ${panel.mode === 'add' ? 'provisioned' : 'updated'} successfully.`); } catch (failure) { setError(adminApiErrorMessage(failure, 'Unable to save the Staff account.')); } finally { setSaving(false); } }
  async function changeStatus(account) { if (saving) return; setSaving(true); setError(''); try { const updated = await adminApiService.setStaffStatus(account); setMessage(`${updated.display_name}'s account is now ${updated.status}.`); setPanel(current => current?.account?.id === updated.id ? { mode: 'view', account: updated } : current); setReload(value => value + 1); } catch (failure) { setError(adminApiErrorMessage(failure, 'Unable to update this Staff account.')); } finally { setSaving(false); } }
  const setField = (field, value) => setForm(current => ({ ...current, [field]: value }));
  return <div className="manage-doctors">
    <header className="md-heading"><div><h1>Manage Staff</h1><p>Provision Staff accounts and manage approved profile information and portal access.</p></div><button className="action-link" onClick={() => open('add')}>Add Staff</button></header>
    <p className="md-hint">Account changes are saved through the clinic API. Deactivation preserves the Staff identity and history.</p>
    {message && <p className="md-success" role="status">{message}</p>}{error && <p className="md-error" role="alert">{error}</p>}
    <div className={`md-layout ${panel ? 'md-with-panel' : ''}`}><section className="md-card" aria-label="Staff list">
      <FormField label="Search by staff name, email, or contact number" name="staff-search" type="search" value={search} onChange={event => { setSearch(event.target.value); setPage(1); }} />
      {list.loading ? <p role="status">Loading Staff accounts…</p> : list.error ? <><p className="md-error" role="alert">{list.error}</p><button className="action-link" onClick={() => setReload(value => value + 1)}>Try again</button></> : <><p>{list.total} staff {list.total === 1 ? 'account' : 'accounts'}</p>{list.items.length ? <ul className="md-list">{list.items.map(account => <li key={account.id}><div className="md-account-summary"><div className="md-name-line"><h2>{account.display_name}</h2><Status value={account.status} /></div><p>{account.email}</p><p>{account.contact_number}</p><p className="md-id">Staff ID: {account.id}</p></div><div className="md-actions"><button className="action-link" aria-label={`View ${account.display_name}`} onClick={() => open('view', account)}>View</button><button className="action-link" aria-label={`Edit ${account.display_name}`} onClick={() => open('edit', account)}>Edit</button><button className="action-link" disabled={saving} onClick={() => changeStatus(account)}>{account.status === 'active' ? 'Deactivate' : 'Reactivate'}</button></div></li>)}</ul> : <p role="status">{search.trim() ? 'No staff match your search.' : 'No Staff accounts yet. Add Staff to get started.'}</p>}{list.pageCount > 1 && <nav className="md-pagination" aria-label="Staff list pages"><button className="action-link" disabled={list.page === 1} onClick={() => setPage(value => Math.max(1, value - 1))}>Previous</button><span>Page {list.page} of {list.pageCount}</span><button className="action-link" disabled={list.page === list.pageCount} onClick={() => setPage(value => Math.min(list.pageCount, value + 1))}>Next</button></nav>}</>}
    </section>
    {panel && <section className="md-card" aria-labelledby="staff-panel-title"><h2 id="staff-panel-title" ref={heading} tabIndex={-1}>{panel.mode === 'add' ? 'Add Staff' : panel.mode === 'edit' ? 'Edit Staff' : 'Staff information'}</h2>{panel.mode === 'view' ? <><dl><dt>Staff name</dt><dd>{panel.account.display_name}</dd><dt>Email</dt><dd>{panel.account.email}</dd><dt>Contact number</dt><dd>{panel.account.contact_number}</dd><dt>Account status</dt><dd><Status value={panel.account.status} /></dd><dt>Staff ID</dt><dd>{panel.account.id}</dd><dt>Role</dt><dd>Staff</dd></dl><div className="md-actions"><button className="action-link" onClick={() => open('edit', panel.account)}>Edit Staff</button><button className="action-link" disabled={saving} onClick={() => changeStatus(panel.account)}>{panel.account.status === 'active' ? 'Deactivate' : 'Reactivate'}</button><button className="action-link" onClick={() => setPanel(null)}>Close</button></div></> : <form onSubmit={save}><p>{panel.mode === 'add' ? 'Provide account credentials and approved Staff profile fields. The Staff role is assigned by the server.' : 'Email and role are fixed. Update approved profile fields only.'}</p>{panel.account && <><p className="md-id">Staff ID: {panel.account.id}</p><p>Email: {panel.account.email}</p></>}{panel.mode === 'add' && <><FormField label="Email" name="staff-email" type="email" required value={form.email} onChange={event => setField('email', event.target.value)} /><FormField label="Temporary password" name="staff-password" type="password" required minLength={8} value={form.password} onChange={event => setField('password', event.target.value)} /></>}<FormField label="Staff name" name="staff-name" required value={form.display_name} onChange={event => setField('display_name', event.target.value)} /><FormField label="Contact number" name="staff-contact" required value={form.contact_number} onChange={event => setField('contact_number', event.target.value)} /><div className="md-actions"><button type="button" className="action-link" disabled={saving} onClick={() => setPanel(null)}>Cancel</button><button type="submit" className="action-link md-primary" disabled={saving}>{saving ? 'Saving…' : 'Save Staff'}</button></div></form>}</section>}
    </div>
  </div>;
}
