import { useEffect, useState } from 'react';
import FormField from '../../components/public/FormField.jsx';
import { adminApiErrorMessage, adminApiService } from '../../services/adminApiService.js';
import '../../styles/admin-doctors.css';

function AccountStatus({ patient }) { if (!patient.has_portal_account) return <span className="account-status account-status-none">No portal account</span>; return <span className={`account-status account-status-${patient.account_status}`}>{patient.account_status}</span>; }
function formatDate(value) { if (!value) return 'Not available'; return new Intl.DateTimeFormat('en-PH', { year: 'numeric', month: 'short', day: 'numeric' }).format(new Date(value)); }

export default function ManagePatients() {
  const [search, setSearch] = useState(''); const [status, setStatus] = useState('all'); const [page, setPage] = useState(1); const [reload, setReload] = useState(0); const [pendingId, setPendingId] = useState(''); const [message, setMessage] = useState(''); const [actionError, setActionError] = useState('');
  const [list, setList] = useState({ loading: true, items: [], total: 0, page: 1, pageCount: 1, error: '' });
  useEffect(() => { let active = true; const timer = setTimeout(async () => { setList(current => ({ ...current, loading: true, error: '' })); try { const result = await adminApiService.listPatients({ search, status, page, limit: 5 }); if (active) setList({ loading: false, ...result, error: '' }); } catch (failure) { if (active) setList({ loading: false, items: [], total: 0, page: 1, pageCount: 1, error: adminApiErrorMessage(failure, 'Unable to load Patient accounts.') }); } }, 200); return () => { active = false; clearTimeout(timer); }; }, [search, status, page, reload]);
  async function updateStatus(patient) { if (pendingId) return; setPendingId(patient.id); setActionError(''); setMessage(''); try { const updated = await adminApiService.setPatientStatus(patient); setMessage(`${updated.full_name}'s portal account is now ${updated.account_status}. Patient ID was preserved.`); setReload(value => value + 1); } catch (failure) { setActionError(adminApiErrorMessage(failure, 'Unable to update this Patient account.')); } finally { setPendingId(''); } }
  return <div className="manage-doctors manage-patients"><header className="md-heading"><div><h1>Manage Patients</h1><p>View basic Patient account information and manage existing portal access.</p></div></header>
    <p className="md-hint">Patients without a portal account remain visible and have no lifecycle action. Clinical information is not available here.</p>{message && <p className="md-success" role="status">{message}</p>}{actionError && <p className="md-error" role="alert">{actionError}</p>}
    <section className="md-card" aria-label="Patient account list"><div className="md-filter-grid"><FormField label="Search by patient name or contact number" name="admin-patient-search" type="search" value={search} onChange={event => { setSearch(event.target.value); setPage(1); }} /><FormField label="Account status" name="admin-patient-status" value={status} onChange={event => { setStatus(event.target.value); setPage(1); }}><option value="all">All patients</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="no_account">No portal account</option></FormField></div>
      {list.loading ? <p role="status">Loading Patient accounts…</p> : list.error ? <><p className="md-error" role="alert">{list.error}</p><button className="action-link" onClick={() => setReload(value => value + 1)}>Try again</button></> : <><p>{list.total} {list.total === 1 ? 'patient' : 'patients'}</p>{list.items.length ? <ul className="md-list">{list.items.map(patient => <li key={patient.id}><div className="md-account-summary"><div className="md-name-line"><h2>{patient.full_name}</h2><AccountStatus patient={patient} /></div><p>{patient.contact_number}</p><p>{patient.has_portal_account ? `Account created: ${formatDate(patient.account_created_at)}` : 'Walk-in/guest Patient'}</p><p className="md-id">Patient ID: {patient.id}</p></div>{patient.has_portal_account && <div className="md-actions"><button className="action-link" disabled={Boolean(pendingId)} onClick={() => updateStatus(patient)}>{pendingId === patient.id ? 'Updating…' : patient.account_status === 'active' ? 'Deactivate' : 'Reactivate'}</button></div>}</li>)}</ul> : <p role="status">{search.trim() || status !== 'all' ? 'No patients match the selected search and status.' : 'No patients are available.'}</p>}{list.pageCount > 1 && <nav className="md-pagination" aria-label="Patient list pages"><button className="action-link" disabled={list.page === 1} onClick={() => setPage(value => Math.max(1, value - 1))}>Previous</button><span>Page {list.page} of {list.pageCount}</span><button className="action-link" disabled={list.page === list.pageCount} onClick={() => setPage(value => Math.min(list.pageCount, value + 1))}>Next</button></nav>}</>}
    </section>
  </div>;
}
